"""
R41 Lead B: Does the iterated-commutator algebra generated by
{Q_W, T_p, X_p=[Q_W,T_p]} CLOSE in a finite-dimensional Lie algebra?

We build the bracket-span level by level on the (2N+1)x(2N+1) matrix space
and on its EVEN-subspace projection, tracking the dimension at each level.

Stabilization => finite Lie algebra (we then look at structure).
Polynomial growth in level => polynomial-growth Lie algebra.
Exponential growth => free.

Reuses build_Tp_shift / connes_consani_fourier_weil_matrix.
"""
import numpy as np
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from r38_krein_rutman_rh import connes_consani_fourier_weil_matrix
from r39_commutator import even_projector
from r40p1_hecke_commutator import build_Tp_shift


def mat_to_vec(M):
    return M.reshape(-1)


def lin_independent_append(basis_vecs, M, tol=1e-9):
    """Append vec(M) to basis_vecs if it raises rank.
    basis_vecs: list of 1D complex arrays (already orthonormalized via QR rebuilds).
    Returns (added: bool, new_basis_vecs).
    """
    v = mat_to_vec(M).astype(complex)
    if basis_vecs:
        B = np.stack(basis_vecs, axis=1)  # (D, k)
        # Project out
        coeffs = B.conj().T @ v
        v = v - B @ coeffs
    nrm = np.linalg.norm(v)
    if nrm < tol:
        return False, basis_vecs
    v = v / nrm
    return True, basis_vecs + [v]


def comm(A, B):
    return A @ B - B @ A


def closure_levels(generators, max_level=6, tol=1e-9, max_dim=None, verbose=True,
                   label=""):
    """Build the Lie-algebra closure level by level.

    Level 0 = generators.
    Level k+1 = level k ∪ { [g, x] : g in generators, x in level k } added if
                linearly independent.
    Stops when no new directions appear (closed) or max_level reached.
    """
    basis = []
    levels_dims = []
    current = []  # matrices at the most recent "frontier"
    # Seed with generators
    for G in generators:
        added, basis = lin_independent_append(basis, G, tol)
        if added:
            current.append(G)
    levels_dims.append(len(basis))
    if verbose:
        print(f"  [{label}] level 0 (generators): dim = {len(basis)}")

    for level in range(1, max_level + 1):
        new_frontier = []
        for g in generators:
            for x in current:
                C = comm(g, x)
                if np.linalg.norm(C) < tol:
                    continue
                added, basis = lin_independent_append(basis, C, tol)
                if added:
                    new_frontier.append(C)
                    if max_dim is not None and len(basis) >= max_dim:
                        break
            if max_dim is not None and len(basis) >= max_dim:
                break
        levels_dims.append(len(basis))
        if verbose:
            print(f"  [{label}] level {level}: dim = {len(basis)}  (added {len(new_frontier)})")
        if not new_frontier:
            if verbose:
                print(f"  [{label}] CLOSED at level {level}, total dim = {len(basis)}")
            return levels_dims, basis, True
        current = new_frontier
        if max_dim is not None and len(basis) >= max_dim:
            if verbose:
                print(f"  [{label}] HIT max_dim cap = {max_dim}")
            return levels_dims, basis, False
    if verbose:
        print(f"  [{label}] not closed by level {max_level}, dim = {len(basis)}")
    return levels_dims, basis, False


def run_case(lam, N_modes, primes, max_level=6, tol=1e-9, max_dim_frac=0.9):
    print("\n" + "="*78)
    print(f"  λ={lam}  N_modes={N_modes}  #primes={len(primes)}  primes={primes}")
    print("="*78)
    Q_W, _, _, _ = connes_consani_fourier_weil_matrix(lam, N_modes, primes)
    Q_W = Q_W.astype(complex)
    D = Q_W.shape[0]
    print(f"  matrix dim D = {D}, ambient gl(D) dim = {D*D}")
    P_even = even_projector(N_modes).astype(complex)

    Tps = [build_Tp_shift(N_modes, lam, p, symmetric=True) for p in primes]
    Xps = [comm(Q_W, Tp) for Tp in Tps]
    print("  ‖X_p‖ = [", ", ".join(f"{np.linalg.norm(X,2):.3e}" for X in Xps), "]")

    # Iterated commutator samples (level 1 brackets, sanity)
    print("\n  Sample iterated brackets:")
    for i, p in enumerate(primes[:3]):
        print(f"    ‖[Q,X_{p}]‖ = {np.linalg.norm(comm(Q_W, Xps[i]),2):.3e}")
        for j, q in enumerate(primes[:3]):
            if j == i: continue
            print(f"    ‖[T_{p},X_{q}]‖ = {np.linalg.norm(comm(Tps[i], Xps[j]),2):.3e}"
                  f"   ‖[X_{p},X_{q}]‖ = {np.linalg.norm(comm(Xps[i], Xps[j]),2):.3e}")

    generators = [Q_W] + Tps + Xps
    cap = int(max_dim_frac * D * D)

    print("\n  --- FULL space closure ---")
    dims_full, basis_full, closed_full = closure_levels(
        generators, max_level=max_level, tol=tol, max_dim=cap,
        label="full")

    # EVEN subspace: project everything
    print("\n  --- EVEN subspace closure ---")
    Q_e = P_even @ Q_W @ P_even
    Tps_e = [P_even @ T @ P_even for T in Tps]
    Xps_e = [comm(Q_e, T) for T in Tps_e]
    gens_e = [Q_e] + Tps_e + Xps_e
    dims_even, basis_even, closed_even = closure_levels(
        gens_e, max_level=max_level, tol=tol, max_dim=cap,
        label="even")

    return dict(D=D, dims_full=dims_full, closed_full=closed_full,
                dims_even=dims_even, closed_even=closed_even)


if __name__ == "__main__":
    print("R41 Lead B: Lie-algebra closure of {Q_W, T_p, X_p=[Q_W,T_p]}")
    cases = [
        (3.6, 20, [2, 3, 5, 7, 11]),
        (6.0, 25, [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]),
        (10.0, 30, [2, 3, 5, 7, 11, 13, 17, 19, 23, 29,
                    31, 37, 41, 43, 47, 53, 59, 61, 67, 71]),
    ]
    results = []
    for lam, N, primes in cases:
        sys.stdout.flush()
        r = run_case(lam, N, primes, max_level=5)
        sys.stdout.flush()
        results.append((lam, N, len(primes), r))

    print("\n" + "#"*78)
    print("# SUMMARY")
    print("#"*78)
    print(f"  {'lam':>5} {'N':>4} {'#p':>4} {'D':>5} {'D^2':>7}  full dims (per level)         even dims")
    for lam, N, np_, r in results:
        df = ",".join(str(d) for d in r['dims_full'])
        de = ",".join(str(d) for d in r['dims_even'])
        cf = "C" if r['closed_full'] else "."
        ce = "C" if r['closed_even'] else "."
        print(f"  {lam:>5} {N:>4} {np_:>4} {r['D']:>5} {r['D']**2:>7}  [{cf}] {df:30s}  [{ce}] {de}")
