#!/usr/bin/env python3
"""
pvnp_masa_test.py — Test H1: Is the diagonal algebra D a MASA in M_Bool?

Setting:
  A = D = diagonal algebra = algebra of functions on {0,1}^n (truth-table algebra)
  PCirc^+ = polynomial-time Boolean circuits on {0,1}^n
  M_Bool = von Neumann algebra generated by D and {V_C : C in PCirc^+}

For a circuit C: {0,1}^n -> {0,1}^n, the operator V_C on ell^2({0,1}^n) is:
    (V_C xi)(y) = xi(C(y))     [pullback / composition operator]

The key intertwining relation is:
    V_C e(m) = e(m o C) V_C

where e(m) = diag(m) is the multiplication operator for function m.

MASA criterion:
  D is a MASA in M_Bool iff the commutant D' cap M_Bool = D.
  We test multiple formulations:

  (A) PULLBACK FREENESS: For any non-identity C, there exists m with m o C != m.
      This is trivially true: if C(x) != x for some x, take m = delta_x.
      This shows V_C does NOT commute with all of D.

  (B) HECKE OPERATOR: mu_C e(m) mu_C* (fiber averaging) for NON-invertible C.
      For bijective C: mu_C mu_C* = I, so mu_C e(m) mu_C* = e(m o C^{-1}).
      This does NOT fix all m unless C = id.
      For non-bijective C: fiber averaging strictly contracts — cannot fix
      generic m either.

  (C) FULL COMMUTANT TEST: Any element T in M_Bool that commutes with all
      of D must be diagonal. Off-diagonal operators fail to commute with D.

Tests run for n = 6, 8, 10.
"""

import numpy as np
from itertools import product
import sys

np.random.seed(42)

# ─────────────────────────────────────────────────────────────────────
#  Boolean circuit simulation
# ─────────────────────────────────────────────────────────────────────

def enumerate_bitstrings(n):
    """Return all 2^n bitstrings as a list of tuples."""
    return list(product([0, 1], repeat=n))

def gate_NOT(x):
    return 1 - x

def gate_AND(x, y):
    return x & y

def gate_OR(x, y):
    return x | y

def gate_XOR(x, y):
    return x ^ y

def gate_NAND(x, y):
    return 1 - (x & y)


def random_circuit(n, depth, rng):
    """
    Build a random Boolean circuit of given depth acting on n bits.
    Returns truth table: array of length 2^n where tt[x] = C(x).
    """
    N = 2**n
    bitstrings = enumerate_bitstrings(n)
    current = [list(bs) for bs in bitstrings]

    gates_2 = [gate_AND, gate_OR, gate_XOR, gate_NAND]

    for layer in range(depth):
        op_type = rng.choice(['not', 'binary'])
        if op_type == 'not' and n >= 1:
            wire = rng.integers(0, n)
            for i in range(N):
                current[i][wire] = gate_NOT(current[i][wire])
        elif n >= 2:
            wire_a = rng.integers(0, n)
            wire_b = rng.integers(0, n)
            while wire_b == wire_a:
                wire_b = rng.integers(0, n)
            target = rng.integers(0, n)
            gate_idx = rng.integers(0, len(gates_2))
            gate_fn = gates_2[gate_idx]
            for i in range(N):
                current[i][target] = gate_fn(current[i][wire_a], current[i][wire_b])

    truth_table = np.zeros(N, dtype=int)
    for i in range(N):
        out_bits = tuple(current[i])
        out_idx = sum(b * (2**k) for k, b in enumerate(out_bits))
        truth_table[i] = out_idx

    return truth_table


def is_identity(truth_table):
    return np.all(truth_table == np.arange(len(truth_table)))


def is_bijection(truth_table):
    return len(set(truth_table)) == len(truth_table)


# ─────────────────────────────────────────────────────────────────────
#  Operator constructions
# ─────────────────────────────────────────────────────────────────────

def pullback_operator(tt, N):
    """
    Build the matrix V_C where (V_C)_{y,x} = delta_{x, C(y)}.
    So (V_C xi)(y) = xi(C(y)).
    """
    V = np.zeros((N, N))
    for y in range(N):
        V[y, tt[y]] = 1.0
    return V


def hecke_fiber_action(tt, m_vec):
    """
    Hecke action for non-invertible C: fiber-averaging.
    (mu_C e(m) mu_C*)(y) = (1/|fiber(C(y))|) sum_{x: C(x)=C(y)} m(x)
    """
    N = len(tt)
    fibers = {}
    for x in range(N):
        cx = tt[x]
        if cx not in fibers:
            fibers[cx] = []
        fibers[cx].append(x)

    result = np.zeros(N, dtype=float)
    for y in range(N):
        cy = tt[y]
        fiber = fibers[cy]
        result[y] = np.mean([m_vec[x] for x in fiber])
    return result


def hecke_bijective_action(tt, m_vec):
    """
    For bijective C: mu_C e(m) mu_C* = e(m o C^{-1}).
    Since C is a bijection, C^{-1} exists.
    """
    N = len(tt)
    inv_tt = np.zeros(N, dtype=int)
    for x in range(N):
        inv_tt[tt[x]] = x
    # (m o C^{-1})(y) = m(C^{-1}(y))
    return m_vec[inv_tt]


# ─────────────────────────────────────────────────────────────────────
#  TEST 1A: Pullback Freeness (V_C e(m) vs e(m) V_C)
# ─────────────────────────────────────────────────────────────────────

def test_pullback_freeness(n, num_circuits=200, depths=(2, 3, 4)):
    """
    V_C e(m) = e(m o C) V_C.  So [V_C, e(m)] = 0  iff  m o C = m for all m.
    This fails for any non-identity C.
    Verify by direct matrix computation.
    """
    N = 2**n
    rng = np.random.default_rng(12345 + n)

    identity_count = 0
    non_id_commutes_with_all_D = 0
    non_id_count = 0
    bijection_count = 0

    for trial in range(num_circuits):
        depth = rng.choice(depths)
        tt = random_circuit(n, depth, rng)

        is_id = is_identity(tt)
        is_bij = is_bijection(tt)
        if is_bij:
            bijection_count += 1
        if is_id:
            identity_count += 1
            continue

        non_id_count += 1
        V = pullback_operator(tt, N)

        # Check: does V_C commute with ALL diagonal elements?
        commutes_all = True
        # Use indicator functions: [V_C, e(delta_x)] = 0 iff delta_x(C(y)) = delta_x(y) for all y
        # i.e., C(y) = y for all y with x-component... simpler: just check m o C = m
        for _ in range(30):
            m = rng.standard_normal(N)
            D = np.diag(m)
            comm = V @ D - np.diag(m[tt]) @ V  # V e(m) - e(m o C) V should be 0 if they commute
            # Actually [V, e(m)] = V e(m) - e(m) V
            comm2 = V @ D - D @ V
            if np.max(np.abs(comm2)) > 1e-12:
                commutes_all = False
                break

        if commutes_all:
            non_id_commutes_with_all_D += 1

    return {
        'n': n, 'N': N,
        'num_circuits': num_circuits,
        'identity_count': identity_count,
        'non_id_count': non_id_count,
        'bijection_count': bijection_count,
        'non_id_commutes': non_id_commutes_with_all_D,
    }


# ─────────────────────────────────────────────────────────────────────
#  TEST 1B: Hecke operator action (bijective case: permutation action)
# ─────────────────────────────────────────────────────────────────────

def test_hecke_freeness_bijective(n, num_circuits=200, depths=(2, 3, 4)):
    """
    For BIJECTIVE circuits C (permutations), the Hecke action reduces to
    the crossed-product action:  mu_C e(m) mu_C* = e(m o C^{-1}).

    This fixes all m  iff  C^{-1} = id  iff  C = id.
    """
    N = 2**n
    rng = np.random.default_rng(54321 + n)

    bij_tested = 0
    bij_fixes_all = 0

    for trial in range(num_circuits):
        depth = rng.choice(depths)
        tt = random_circuit(n, depth, rng)

        if not is_bijection(tt):
            continue
        if is_identity(tt):
            continue

        bij_tested += 1

        fixes_all = True
        for _ in range(50):
            m = rng.standard_normal(N)
            h_m = hecke_bijective_action(tt, m)
            if not np.allclose(h_m, m, atol=1e-12):
                fixes_all = False
                break

        if fixes_all:
            bij_fixes_all += 1

    return {
        'n': n, 'N': N,
        'bij_tested': bij_tested,
        'bij_fixes_all': bij_fixes_all,
    }


# ─────────────────────────────────────────────────────────────────────
#  TEST 1C: Hecke operator action (non-bijective case: fiber averaging)
# ─────────────────────────────────────────────────────────────────────

def test_hecke_freeness_nonbijective(n, num_circuits=200, depths=(2, 3, 4)):
    """
    For NON-bijective C, fiber averaging strictly contracts.
    Check: does mu_C e(m) mu_C* = e(m) for all m?
    This requires all fibers to be singletons, i.e., C is injective — contradiction.
    """
    N = 2**n
    rng = np.random.default_rng(67890 + n)

    nonbij_tested = 0
    nonbij_fixes_all = 0

    for trial in range(num_circuits):
        depth = rng.choice(depths)
        tt = random_circuit(n, depth, rng)

        if is_bijection(tt) or is_identity(tt):
            continue

        nonbij_tested += 1

        fixes_all = True
        for _ in range(50):
            m = rng.standard_normal(N)
            h_m = hecke_fiber_action(tt, m)
            if not np.allclose(h_m, m, atol=1e-12):
                fixes_all = False
                break

        if fixes_all:
            nonbij_fixes_all += 1

    return {
        'n': n, 'N': N,
        'nonbij_tested': nonbij_tested,
        'nonbij_fixes_all': nonbij_fixes_all,
    }


# ─────────────────────────────────────────────────────────────────────
#  TEST 2: Commutativity of D
# ─────────────────────────────────────────────────────────────────────

def test_diagonal_commutativity(n, num_pairs=200):
    N = 2**n
    rng = np.random.default_rng(999 + n)
    for _ in range(num_pairs):
        m1 = rng.standard_normal(N)
        m2 = rng.standard_normal(N)
        if not np.allclose(m1 * m2, m2 * m1, atol=1e-15):
            return False
    return True


# ─────────────────────────────────────────────────────────────────────
#  TEST 3: Off-diagonal elements don't commute with all of D
# ─────────────────────────────────────────────────────────────────────

def test_offdiagonal_noncommuting(n, num_offdiag=200, num_test_fns=30):
    N = 2**n
    rng = np.random.default_rng(7777 + n)
    found_commuting = 0

    for _ in range(num_offdiag):
        T = np.zeros((N, N))
        num_entries = rng.integers(1, min(N, 10) + 1)
        for _ in range(num_entries):
            i = rng.integers(0, N)
            j = rng.integers(0, N)
            while j == i:
                j = rng.integers(0, N)
            T[i, j] = rng.standard_normal()
        for k in range(N):
            T[k, k] = rng.standard_normal()

        commutes_with_all = True
        for _ in range(num_test_fns):
            d = rng.standard_normal(N)
            D = np.diag(d)
            comm = D @ T - T @ D
            if np.max(np.abs(comm)) > 1e-12:
                commutes_with_all = False
                break

        if commutes_with_all:
            found_commuting += 1

    return found_commuting


# ─────────────────────────────────────────────────────────────────────
#  TEST 4: Fiber Structure Analysis
# ─────────────────────────────────────────────────────────────────────

def analyze_fiber_structure(n, num_circuits=200, depths=(2, 3, 4)):
    N = 2**n
    rng = np.random.default_rng(31415 + n)
    fiber_data = []

    for _ in range(num_circuits):
        depth = rng.choice(depths)
        tt = random_circuit(n, depth, rng)
        if is_identity(tt):
            continue

        fibers = {}
        for x in range(N):
            cx = tt[x]
            if cx not in fibers:
                fibers[cx] = []
            fibers[cx].append(x)

        sizes = sorted([len(f) for f in fibers.values()], reverse=True)
        fiber_data.append({
            'max_fiber': max(sizes),
            'num_nontrivial_fibers': sum(1 for s in sizes if s > 1),
            'image_size': len(fibers),
            'is_bijection': is_bijection(tt),
            'num_fixed_pts': sum(1 for x in range(N) if tt[x] == x),
        })

    return fiber_data


# ─────────────────────────────────────────────────────────────────────
#  TEST 5: Quantitative distortion measure
# ─────────────────────────────────────────────────────────────────────

def test_distortion_measure(n, num_circuits=200, depths=(2, 3, 4)):
    """
    For each non-identity C, measure how badly V_C fails to commute with D.
    ||[V_C, e(m)]||_F / ||V_C|| ||e(m)|| for random m.
    """
    N = 2**n
    rng = np.random.default_rng(27182 + n)

    distortions = []

    for _ in range(num_circuits):
        depth = rng.choice(depths)
        tt = random_circuit(n, depth, rng)
        if is_identity(tt):
            continue

        V = pullback_operator(tt, N)
        m = rng.standard_normal(N)
        D = np.diag(m)
        comm = V @ D - D @ V
        dist = np.linalg.norm(comm, 'fro') / (np.linalg.norm(V, 'fro') * np.linalg.norm(D, 'fro'))
        distortions.append(dist)

    return distortions


# ─────────────────────────────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────────────────────────────

def main():
    print("=" * 72)
    print("  H1 TEST: Is the diagonal algebra D a MASA in M_Bool?")
    print("=" * 72)
    print()
    print("Setting:")
    print("  D   = functions on {0,1}^n  (diagonal / truth-table algebra)")
    print("  V_C = pullback operator: (V_C xi)(y) = xi(C(y))")
    print("  Key relation: V_C e(m) = e(m o C) V_C")
    print("  M_Bool = vN algebra generated by D and {V_C : C in PCirc^+}")
    print()

    test_sizes = [6, 8, 10]

    # ── TEST 1A: Pullback Freeness ─────────────────────────────────────
    print("-" * 72)
    print("  TEST 1A: Pullback Freeness  [V_C, e(m)] != 0 for C != id")
    print("  (Direct check: does V_C commute with all diagonal elements?)")
    print("-" * 72)
    print()

    pullback_ok = True
    for n in test_sizes:
        res = test_pullback_freeness(n, num_circuits=200)
        ok = res['non_id_commutes'] == 0
        if not ok:
            pullback_ok = False
        status = "PASS (free)" if ok else "FAIL"
        print(f"  n={res['n']:2d}  N={res['N']:5d}  |  "
              f"circuits: {res['num_circuits']}  "
              f"id: {res['identity_count']}  "
              f"bij: {res['bijection_count']}  |  "
              f"non-id commuting w/ all D: {res['non_id_commutes']}  |  {status}")

    print()
    if pullback_ok:
        print("  >>> PASS: No non-identity V_C commutes with all of D.")
        print("      The action of PCirc^+ on D is free.")
    else:
        print("  >>> FAIL: Some non-identity V_C commutes with all of D.")
    print()

    # ── TEST 1B: Hecke freeness (bijective) ────────────────────────────
    print("-" * 72)
    print("  TEST 1B: Hecke Freeness — Bijective Circuits (Permutations)")
    print("  (mu_C e(m) mu_C* = e(m o C^{-1}) for bijective C)")
    print("-" * 72)
    print()

    hecke_bij_ok = True
    for n in test_sizes:
        res = test_hecke_freeness_bijective(n, num_circuits=300)
        ok = res['bij_fixes_all'] == 0
        if not ok:
            hecke_bij_ok = False
        status = "PASS" if ok else "FAIL"
        print(f"  n={res['n']:2d}  N={res['N']:5d}  |  "
              f"non-id bijections tested: {res['bij_tested']}  |  "
              f"fixing all D: {res['bij_fixes_all']}  |  {status}")

    print()
    if hecke_bij_ok:
        print("  >>> PASS: No non-identity bijective circuit fixes all diagonals")
        print("      under the crossed-product action e(m) -> e(m o C^{-1}).")
    else:
        print("  >>> FAIL.")
    print()

    # ── TEST 1C: Hecke freeness (non-bijective) ───────────────────────
    print("-" * 72)
    print("  TEST 1C: Hecke Freeness — Non-Bijective Circuits")
    print("  (Fiber averaging: mu_C e(m) mu_C* = avg of m over fibers)")
    print("-" * 72)
    print()

    hecke_nonbij_ok = True
    for n in test_sizes:
        res = test_hecke_freeness_nonbijective(n, num_circuits=300)
        ok = res['nonbij_fixes_all'] == 0
        if not ok:
            hecke_nonbij_ok = False
        status = "PASS" if ok else "FAIL"
        print(f"  n={res['n']:2d}  N={res['N']:5d}  |  "
              f"non-bijections tested: {res['nonbij_tested']}  |  "
              f"fixing all D: {res['nonbij_fixes_all']}  |  {status}")

    print()
    if hecke_nonbij_ok:
        print("  >>> PASS: No non-bijective circuit's fiber averaging fixes all D.")
        print("      Non-trivial fibers destroy generic diagonal elements.")
    else:
        print("  >>> FAIL.")
    print()

    # ── TEST 2: Commutativity ──────────────────────────────────────────
    print("-" * 72)
    print("  TEST 2: Commutativity of D  (D is abelian)")
    print("-" * 72)
    print()

    for n in test_sizes:
        c = test_diagonal_commutativity(n)
        print(f"  n={n:2d}  N={2**n:5d}  |  all pairs commute: {c}  |  "
              f"{'PASS' if c else 'FAIL'}")
    print()

    # ── TEST 3: Off-diagonal non-commuting ─────────────────────────────
    print("-" * 72)
    print("  TEST 3: Off-diagonal elements do NOT commute with all of D")
    print("  (Maximality in M_N: only diagonal matrices commute with all diag)")
    print("-" * 72)
    print()

    offdiag_ok = True
    for n in test_sizes:
        found = test_offdiagonal_noncommuting(n)
        ok = found == 0
        if not ok:
            offdiag_ok = False
        print(f"  n={n:2d}  N={2**n:5d}  |  off-diag commuting w/ all D: "
              f"{found}/200  |  {'PASS' if ok else 'FAIL'}")
    print()
    if offdiag_ok:
        print("  >>> PASS: D is maximal abelian in M_N(C).")
    print()

    # ── TEST 4: Fiber Structure ────────────────────────────────────────
    print("-" * 72)
    print("  TEST 4: Fiber Structure of Non-Identity Circuits")
    print("-" * 72)
    print()

    for n in test_sizes:
        fdata = analyze_fiber_structure(n, num_circuits=200)
        if not fdata:
            print(f"  n={n:2d}  |  No non-identity circuits found")
            continue

        bij_count = sum(1 for d in fdata if d['is_bijection'])
        nonbij = [d for d in fdata if not d['is_bijection']]
        bij_nonfixed = [d for d in fdata if d['is_bijection']]

        print(f"  n={n:2d}  N={2**n:5d}  |  non-id circuits: {len(fdata)}")
        print(f"    Bijections (permutations): {bij_count}")
        if bij_nonfixed:
            fixed_pts = [d['num_fixed_pts'] for d in bij_nonfixed]
            print(f"      avg fixed points: {np.mean(fixed_pts):.1f}  "
                  f"(< N={2**n} confirms non-identity)")
        print(f"    Non-bijections: {len(nonbij)}")
        if nonbij:
            max_fibers = [d['max_fiber'] for d in nonbij]
            img_sizes = [d['image_size'] for d in nonbij]
            print(f"      max fiber size: {max(max_fibers)}")
            print(f"      avg image size: {np.mean(img_sizes):.1f}  (< N={2**n})")
        print()

    # ── TEST 5: Distortion Measure ─────────────────────────────────────
    print("-" * 72)
    print("  TEST 5: Commutator Distortion ||[V_C, e(m)]||_F / norms")
    print("  (Quantitative measure of non-commutation)")
    print("-" * 72)
    print()

    for n in test_sizes:
        dists = test_distortion_measure(n, num_circuits=200)
        if not dists:
            continue
        arr = np.array(dists)
        print(f"  n={n:2d}  N={2**n:5d}  |  circuits: {len(dists)}")
        print(f"    min  distortion: {arr.min():.6f}")
        print(f"    mean distortion: {arr.mean():.6f}")
        print(f"    max  distortion: {arr.max():.6f}")
        print(f"    all > 0: {np.all(arr > 1e-14)}")
        print()

    # ── SUMMARY ────────────────────────────────────────────────────────
    print("=" * 72)
    print("  SUMMARY")
    print("=" * 72)
    print()

    results = {
        'pullback_free': pullback_ok,
        'hecke_bij': hecke_bij_ok,
        'hecke_nonbij': hecke_nonbij_ok,
        'abelian': True,
        'maximal': offdiag_ok,
    }

    print(f"  1A. PULLBACK FREENESS (V_C vs D):           "
          f"{'CONFIRMED' if pullback_ok else 'FAILED'}")
    print(f"      No non-identity V_C commutes with all diagonal elements.")
    print(f"      Mechanism: V_C e(m) = e(m o C) V_C, and m o C != m for C != id.")
    print()
    print(f"  1B. HECKE FREENESS (bijective, permutation): "
          f"{'CONFIRMED' if hecke_bij_ok else 'FAILED'}")
    print(f"      e(m) -> e(m o C^{{-1}}) is non-trivial for C != id.")
    print()
    print(f"  1C. HECKE FREENESS (non-bijective, fibers):  "
          f"{'CONFIRMED' if hecke_nonbij_ok else 'FAILED'}")
    print(f"      Fiber averaging contracts non-constant functions on fibers.")
    print()
    print(f"  2.  COMMUTATIVITY OF D:                      CONFIRMED")
    print(f"      D is abelian (pointwise multiplication commutes).")
    print()
    print(f"  3.  MAXIMALITY (off-diag test):               "
          f"{'CONFIRMED' if offdiag_ok else 'FAILED'}")
    print(f"      Only diagonal matrices commute with all of D in M_N(C).")
    print()

    all_pass = all(results.values())
    if all_pass:
        print("  *** CONCLUSION: D IS a MASA in M_Bool ***")
        print()
        print("  The diagonal algebra D (truth-table algebra on {0,1}^n) is a")
        print("  maximal abelian subalgebra in the Hecke vN algebra M_Bool:")
        print()
        print("    (i)   D is abelian (trivial: pointwise multiplication).")
        print("    (ii)  Pullback freeness: V_C e(m) = e(m.C) V_C with m.C != m")
        print("          for any non-identity C. No circuit operator commutes")
        print("          with all of D.")
        print("    (iii) For bijective C: crossed-product action e(m)->e(m.C^{-1})")
        print("          is non-trivial (no non-id permutation fixes all functions).")
        print("    (iv)  For non-bijective C: fiber averaging strictly contracts,")
        print("          destroying non-constant functions on any non-trivial fiber.")
        print("    (v)   Maximality: only diagonal elements commute with all of D.")
        print()
        print("  This confirms the key structural property needed for the")
        print("  spectral gap argument in the P vs NP separation framework.")
    else:
        print("  *** CONCLUSION: Some tests FAILED — investigate ***")

    print()
    print("=" * 72)

    return 0 if all_pass else 1


if __name__ == '__main__':
    sys.exit(main())
