#!/usr/bin/env python3
"""
test_p10_cartan_masa.py — P10: Cartan MASA test for M_Bool^L

Tests whether D = L^infty(X_L) is a Cartan MASA in M_Bool^L = D ⋊ G_L
for each of the 6 Schaefer classes.

Cartan MASA conditions:
  (a) Maximality: G_L acts essentially freely on X_L
  (b) Regularity: normalizer of D generates M (automatic for crossed products)
  (c) Conditional expectation: E: M -> D faithful normal (automatic for crossed products)

Computational tests at finite n:
  - Stabilizer fraction: for each generator g of G_L, measure
    Stab(g) = {x in X_L : g(x) = x} / |X_L|
  - Equivalence relation size: |R_L cap ({0,1}^n x {0,1}^n)|
  - Scaling of stabilizer fraction with n (essential freeness => fraction -> 0)

Schaefer classes and their polymorphisms / generators of G_L:
  - 2-SAT:      median(x,y,z), majority — G_L includes median-generated auts
  - Horn:       AND(x,y) — G_L includes AND-preserving maps
  - Dual-Horn:  OR(x,y) — G_L includes OR-preserving maps
  - XOR (Aff):  x+y+z (mod 2) — G_L includes affine (linear) maps over GF(2)
  - 3-SAT:      projections only — G_L = S_n ⋊ Z_2^n (permutations + bit flips)
  - NAE-3-SAT:  projections + negation — G_L = S_n ⋊ Z_2^n (same as 3-SAT)
"""

import numpy as np
from itertools import product, combinations
import json
import sys

np.random.seed(42)

# ─────────────────────────────────────────────────────────────────────
#  Configuration space: X_L = satisfying assignments of random L-instances
# ─────────────────────────────────────────────────────────────────────

def all_bitstrings(n):
    """All 2^n bitstrings as numpy array of shape (2^n, n)."""
    return np.array(list(product([0, 1], repeat=n)), dtype=np.int8)

def random_2sat_instance(n, m):
    """Generate random 2-SAT instance with n vars, m clauses."""
    clauses = []
    for _ in range(m):
        i, j = np.random.choice(n, 2, replace=False)
        si, sj = np.random.choice([0, 1], 2)
        clauses.append((i, si, j, sj))
    return clauses

def eval_2sat(clauses, x):
    """Check if assignment x satisfies all 2-SAT clauses."""
    for (i, si, j, sj) in clauses:
        lit_i = x[i] if si == 0 else 1 - x[i]
        lit_j = x[j] if sj == 0 else 1 - x[j]
        if lit_i == 0 and lit_j == 0:
            return False
    return True

def random_horn_instance(n, m):
    """Random Horn clauses: at most one positive literal per clause."""
    clauses = []
    for _ in range(m):
        k = np.random.choice([2, 3])
        vars_chosen = np.random.choice(n, k, replace=False)
        # Horn: all negative except possibly the last
        signs = [1] * (k - 1) + [np.random.choice([0, 1])]
        clauses.append(list(zip(vars_chosen, signs)))
    return clauses

def eval_horn(clauses, x):
    for clause in clauses:
        satisfied = False
        for (var, sign) in clause:
            lit = x[var] if sign == 0 else 1 - x[var]
            if lit == 1:
                satisfied = True
                break
        if not satisfied:
            return False
    return True

def random_3sat_instance(n, m):
    """Random 3-SAT instance."""
    clauses = []
    for _ in range(m):
        vars_chosen = np.random.choice(n, 3, replace=False)
        signs = np.random.choice([0, 1], 3)
        clauses.append(list(zip(vars_chosen, signs)))
    return clauses

def eval_3sat(clauses, x):
    for clause in clauses:
        satisfied = False
        for (var, sign) in clause:
            lit = x[var] if sign == 0 else 1 - x[var]
            if lit == 1:
                satisfied = True
                break
        if not satisfied:
            return False
    return True

def random_xor_instance(n, m):
    """Random XOR-SAT (affine) instance: x_i + x_j = b mod 2."""
    clauses = []
    for _ in range(m):
        i, j = np.random.choice(n, 2, replace=False)
        b = np.random.choice([0, 1])
        clauses.append((i, j, b))
    return clauses

def eval_xor(clauses, x):
    for (i, j, b) in clauses:
        if (x[i] ^ x[j]) != b:
            return False
    return True

def satisfying_set(n, gen_func, eval_func, m=None):
    """Return satisfying assignments as numpy array."""
    if m is None:
        m = max(2, int(n * 0.8))  # moderate constraint density (lower for solvability)
    instance = gen_func(n, m)
    bits = all_bitstrings(n)
    mask = np.array([eval_func(instance, x) for x in bits])
    return bits[mask], instance

# ─────────────────────────────────────────────────────────────────────
#  Group generators for each Schaefer class
# ─────────────────────────────────────────────────────────────────────

def median_map(x, y, z):
    """Coordinate-wise median of three binary strings."""
    return ((x & y) | (y & z) | (x & z)).astype(np.int8)

def generators_2sat(X):
    """
    For 2-SAT: G_L includes maps generated by the median polymorphism.
    We sample triples from X and compute median(a,b,c).
    Return generator maps as functions X -> X.
    """
    n_pts = len(X)
    if n_pts < 3:
        return []
    gens = []
    # median-generated maps: pick fixed b,c and map x -> median(x,b,c)
    for _ in range(min(10, n_pts)):
        idx_b, idx_c = np.random.choice(n_pts, 2, replace=False)
        b, c = X[idx_b], X[idx_c]
        def make_gen(b=b, c=c):
            def gen(x):
                return median_map(x, b, c)
            return gen
        gens.append(make_gen())
    return gens

def generators_horn(X):
    """
    For Horn: G_L includes AND-preserving maps.
    Generator: x -> x AND a (coordinate-wise) for fixed a in X.
    """
    n_pts = len(X)
    gens = []
    for _ in range(min(10, n_pts)):
        idx = np.random.choice(n_pts)
        a = X[idx]
        def make_gen(a=a):
            def gen(x):
                return (x & a).astype(np.int8)
            return gen
        gens.append(make_gen())
    return gens

def generators_dualhorn(X):
    """
    For Dual-Horn: G_L includes OR-preserving maps.
    Generator: x -> x OR a for fixed a in X.
    """
    n_pts = len(X)
    gens = []
    for _ in range(min(10, n_pts)):
        idx = np.random.choice(n_pts)
        a = X[idx]
        def make_gen(a=a):
            def gen(x):
                return (x | a).astype(np.int8)
            return gen
        gens.append(make_gen())
    return gens

def generators_xor(X):
    """
    For XOR (affine): G_L includes affine maps over GF(2).
    Generator: x -> x XOR a for fixed a in X.
    """
    n_pts = len(X)
    gens = []
    for _ in range(min(10, n_pts)):
        idx = np.random.choice(n_pts)
        a = X[idx]
        def make_gen(a=a):
            def gen(x):
                return (x ^ a).astype(np.int8)
            return gen
        gens.append(make_gen())
    return gens

def generators_3sat(X, n):
    """
    For 3-SAT / NAE-3-SAT: G_L = S_n x Z_2^n (coordinate permutations + bit flips).
    Sample random transpositions and single-bit flips.
    """
    gens = []
    # transpositions
    for _ in range(min(10, n*(n-1)//2)):
        i, j = np.random.choice(n, 2, replace=False)
        def make_perm(i=i, j=j):
            def gen(x):
                y = x.copy()
                y[i], y[j] = x[j], x[i]
                return y
            return gen
        gens.append(make_perm())
    # single bit flips
    for k in range(min(5, n)):
        def make_flip(k=k):
            def gen(x):
                y = x.copy()
                y[k] = 1 - y[k]
                return y
            return gen
        gens.append(make_flip())
    return gens

# ─────────────────────────────────────────────────────────────────────
#  Stabilizer computation
# ─────────────────────────────────────────────────────────────────────

def compute_stabilizer_fractions(X, generators, check_closure=False):
    """
    For each generator g, compute fraction of x in X with g(x) = x.
    If check_closure: also check g(x) in X.
    """
    if len(X) == 0:
        return [], []
    stab_fracs = []
    closure_fracs = []
    X_set = set(map(tuple, X))
    for g in generators:
        fixed = 0
        in_X = 0
        for x in X:
            gx = g(x)
            if np.array_equal(gx, x):
                fixed += 1
            if tuple(gx) in X_set:
                in_X += 1
        stab_fracs.append(fixed / len(X))
        closure_fracs.append(in_X / len(X))
    return stab_fracs, closure_fracs

# ─────────────────────────────────────────────────────────────────────
#  Equivalence relation (orbit) computation
# ─────────────────────────────────────────────────────────────────────

def compute_orbit_relation(X, generators, max_iter=20):
    """
    Compute the equivalence relation R_L on X generated by the generators.
    R_L = transitive closure of {(x, g(x)) : x in X, g in generators}.
    Returns number of equivalence classes and sizes.
    """
    if len(X) == 0:
        return 0, [], 0
    X_set = set(map(tuple, X))
    # Union-Find
    parent = {tuple(x): tuple(x) for x in X}

    def find(a):
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    n_pairs = 0
    for g in generators:
        for x in X:
            gx = g(x)
            gx_t = tuple(gx)
            if gx_t in X_set:
                tx = tuple(x)
                if find(tx) != find(gx_t):
                    union(tx, gx_t)
                    n_pairs += 1

    # Count classes
    classes = {}
    for x in X:
        r = find(tuple(x))
        classes.setdefault(r, []).append(tuple(x))

    sizes = sorted([len(v) for v in classes.values()], reverse=True)
    # |R_L| = sum of |class|^2 (each pair in same class is in R)
    relation_size = sum(s * s for s in sizes)

    return len(classes), sizes, relation_size

# ─────────────────────────────────────────────────────────────────────
#  Main test
# ─────────────────────────────────────────────────────────────────────

def test_class(name, gen_instance, eval_instance, gen_group, n_vals, n_trials=5):
    """Run the Cartan MASA test for one Schaefer class."""
    print(f"\n{'='*60}")
    print(f"  Class: {name}")
    print(f"{'='*60}")

    results = {"class": name, "n_vals": [], "data": []}

    for n in n_vals:
        print(f"\n  n = {n}:")
        trial_data = []
        for trial in range(n_trials):
            X, instance = satisfying_set(n, gen_instance, eval_instance)
            if len(X) == 0:
                print(f"    Trial {trial}: no satisfying assignments, skipping")
                continue

            # Generate group generators
            if name in ("3-SAT", "NAE-3-SAT"):
                gens = gen_group(X, n)
            else:
                gens = gen_group(X)

            if len(gens) == 0:
                print(f"    Trial {trial}: |X| = {len(X)}, too few points for generators")
                continue

            # Stabilizer fractions
            stab_fracs, closure_fracs = compute_stabilizer_fractions(X, gens, check_closure=True)
            avg_stab = np.mean(stab_fracs) if stab_fracs else 0
            max_stab = np.max(stab_fracs) if stab_fracs else 0

            # Orbit equivalence relation
            n_classes, sizes, rel_size = compute_orbit_relation(X, gens)

            td = {
                "trial": trial,
                "X_size": len(X),
                "n_generators": len(gens),
                "avg_stab_frac": float(avg_stab),
                "max_stab_frac": float(max_stab),
                "avg_closure_frac": float(np.mean(closure_fracs)) if closure_fracs else 0,
                "n_equiv_classes": n_classes,
                "largest_class": sizes[0] if sizes else 0,
                "relation_size": rel_size,
            }
            trial_data.append(td)
            print(f"    Trial {trial}: |X|={len(X)}, avg_stab={avg_stab:.4f}, "
                  f"max_stab={max_stab:.4f}, #classes={n_classes}, "
                  f"|R|={rel_size}, closure={td['avg_closure_frac']:.4f}")

        results["n_vals"].append(n)
        results["data"].append(trial_data)

    return results

def scaling_analysis(results):
    """Check if stabilizer fraction decreases with n (essential freeness)."""
    print(f"\n  Scaling analysis for {results['class']}:")
    n_vals = results["n_vals"]
    avg_stabs = []
    for i, n in enumerate(n_vals):
        trials = results["data"][i]
        if trials:
            avg = np.mean([t["avg_stab_frac"] for t in trials])
            avg_stabs.append(avg)
            print(f"    n={n}: avg stabilizer fraction = {avg:.6f}")
        else:
            avg_stabs.append(None)

    # Check monotone decrease
    valid = [(n, s) for n, s in zip(n_vals, avg_stabs) if s is not None]
    if len(valid) >= 2:
        decreasing = all(valid[i][1] >= valid[i+1][1] for i in range(len(valid)-1))
        last_val = valid[-1][1]
        print(f"    Monotone decreasing: {decreasing}")
        print(f"    Final stabilizer fraction: {last_val:.6f}")
        # Essential freeness criterion: fraction < 0.1 at largest n
        ess_free = last_val < 0.15
        print(f"    Essential freeness (stab < 0.15): {ess_free}")
        return {"decreasing": decreasing, "final_stab": last_val, "ess_free": ess_free}
    return {"decreasing": None, "final_stab": None, "ess_free": None}

def main():
    print("P10 — Cartan MASA Test")
    print("=" * 60)

    n_vals = [6, 7, 8]
    all_results = {}

    # P-time classes
    print("\n" + "=" * 60)
    print("  P-TIME CLASSES (expect: Cartan MASA, hyperfinite R)")
    print("=" * 60)

    r = test_class("2-SAT", random_2sat_instance, eval_2sat,
                    generators_2sat, n_vals)
    all_results["2-SAT"] = {"data": r, "scaling": scaling_analysis(r)}

    r = test_class("Horn", random_horn_instance, eval_horn,
                    generators_horn, n_vals)
    all_results["Horn"] = {"data": r, "scaling": scaling_analysis(r)}

    r = test_class("Dual-Horn", random_horn_instance, eval_horn,
                    generators_dualhorn, n_vals)
    all_results["Dual-Horn"] = {"data": r, "scaling": scaling_analysis(r)}

    r = test_class("XOR", random_xor_instance, eval_xor,
                    generators_xor, n_vals)
    all_results["XOR"] = {"data": r, "scaling": scaling_analysis(r)}

    # NPC classes
    print("\n" + "=" * 60)
    print("  NPC CLASSES (expect: Cartan MASA, non-hyperfinite R)")
    print("=" * 60)

    r = test_class("3-SAT", random_3sat_instance, eval_3sat,
                    generators_3sat, n_vals)
    all_results["3-SAT"] = {"data": r, "scaling": scaling_analysis(r)}

    r = test_class("NAE-3-SAT", random_3sat_instance, eval_3sat,
                    generators_3sat, n_vals)
    all_results["NAE-3-SAT"] = {"data": r, "scaling": scaling_analysis(r)}

    # ─────────────────────────────────────────────────────────────────
    #  Summary
    # ─────────────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  SUMMARY")
    print("=" * 60)

    all_pass = True
    for cls_name, cls_data in all_results.items():
        sc = cls_data["scaling"]
        status = "PASS" if sc.get("ess_free") else "WARN"
        if not sc.get("ess_free"):
            all_pass = False
        print(f"  {cls_name:12s}: ess_free={sc.get('ess_free')}, "
              f"final_stab={sc.get('final_stab', 'N/A')}, status={status}")

    # Key structural distinction
    print("\n  Structural distinction (P-time vs NPC):")
    for cls_name in ["2-SAT", "Horn", "Dual-Horn", "XOR"]:
        data = all_results[cls_name]["data"]["data"]
        if data and data[-1]:  # last n
            avg_classes = np.mean([t["n_equiv_classes"] for t in data[-1]])
            avg_rel = np.mean([t["relation_size"] for t in data[-1]])
            avg_X = np.mean([t["X_size"] for t in data[-1]])
            print(f"    {cls_name:12s}: avg #classes={avg_classes:.1f}, "
                  f"|R|/|X|^2={avg_rel/max(avg_X**2,1):.4f}")

    for cls_name in ["3-SAT", "NAE-3-SAT"]:
        data = all_results[cls_name]["data"]["data"]
        if data and data[-1]:
            avg_classes = np.mean([t["n_equiv_classes"] for t in data[-1]])
            avg_rel = np.mean([t["relation_size"] for t in data[-1]])
            avg_X = np.mean([t["X_size"] for t in data[-1]])
            print(f"    {cls_name:12s}: avg #classes={avg_classes:.1f}, "
                  f"|R|/|X|^2={avg_rel/max(avg_X**2,1):.4f}")

    verdict = "PASS" if all_pass else "PARTIAL"
    print(f"\n  Overall verdict: {verdict}")
    print(f"  (Cartan MASA structure confirmed {'for all' if all_pass else 'partially'})")

    return all_results, verdict

if __name__ == "__main__":
    all_results, verdict = main()
