// Auto-generated by visualization/contribution-graph/build.py
// Generated 2026-04-15T01:43:53
// Regenerate: python3 visualization/contribution-graph/build.py

const CONTRIBUTION_DATA = {
  "generated_at": "2026-04-15T01:43:53",
  "generator": "visualization/contribution-graph/build.py",
  "vertices": [
    {
      "key": "qg5d",
      "name": "QG5D",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Alain Connes",
        "Theodor Kaluza & Oskar Klein",
        "Edward Witten",
        "Abhay Ashtekar & Carlo Rovelli",
        "Renate Loll, Jan Ambj\u00f8rn, Jerzy Jurkiewicz",
        "Rafael Sorkin & Fay Dowker",
        "Martin Reuter & Steven Weinberg",
        "Penrose",
        "Maldacena",
        "Susskind",
        "Vafa",
        "Arkani-Hamed"
      ],
      "index": 0,
      "theta": -1.5707963267948966,
      "zone": "NORTH"
    },
    {
      "key": "ym",
      "name": "YM",
      "is_millennium": true,
      "status": "FULL",
      "comply": {
        "present": true,
        "file": "strategy/ym/deliverables/ym-clay-bare.md",
        "lines": 366,
        "theorems": 12,
        "sections": 17,
        "layers": 20,
        "named_walls": [
          "W0",
          "W5",
          "W1",
          "W2",
          "W3"
        ],
        "main_theorem": "Theorem 2.1 (YM Existence and Mass Gap) Let $G$ be any compact simple Lie group. There exists a non-trivial quantum Yang-Mills theory for $G$ on $\\mathbb{R}^4$, satisfying the full Osterwalder-Schrader axioms OS0-OS5 and (by reconstruction) the full Wightman axioms W0-W5, with mass gap"
      },
      "independent": {
        "present": true,
        "file": "strategy/ym/deliverables/ym-independence-bare.md",
        "lines": 495,
        "theorems": 2,
        "sections": 9,
        "primitives": {
          "BYPASS": 9,
          "DECOMPOSE": 38,
          "EXCISE": 1,
          "TRANSPOSE": 1
        },
        "named_walls": [
          "W1 = H4",
          "W1",
          "W2"
        ]
      },
      "contribute": {
        "present": true,
        "file": "strategy/ym/deliverables/ym-harden-bare.md",
        "lines": 429,
        "theorems": 18,
        "sections": 7,
        "externals": [
          {
            "id": "E1",
            "name": "Balaban multi-scale RG",
            "authors": "Ba\u0142aban CMP 95\u2013119 (1982\u201389)"
          },
          {
            "id": "E2",
            "name": "OS reconstruction",
            "authors": "Osterwalder\u2013Schrader CMP 31 (1973); CMP 42 (1975)"
          },
          {
            "id": "E3",
            "name": "Glimm\u2013Jaffe 1987 textbook",
            "authors": "Glimm\u2013Jaffe, *Quantum Physics*, 2nd ed., Springer"
          },
          {
            "id": "E4",
            "name": "Feshbach projection",
            "authors": "Feshbach Ann. Phys. 5 (1958)"
          },
          {
            "id": "E5",
            "name": "Gradient-flow perturbative coefficients",
            "authors": "Harlander\u2013L\u00fcscher et al. arXiv:2111.14376"
          },
          {
            "id": "E6",
            "name": "Reisz power counting",
            "authors": "Reisz CMP 116 (1988); CMP 117 (1988)"
          },
          {
            "id": "E7",
            "name": "L\u00fcscher gradient flow",
            "authors": "L\u00fcscher JHEP 08 (2010) 071; CMP 293 (2010) 899"
          },
          {
            "id": "E8",
            "name": "Osterwalder\u2013Seiler 1978",
            "authors": "Osterwalder\u2013Seiler Ann. Phys. 110 (1978) 440"
          },
          {
            "id": "E9",
            "name": "Magnen\u2013Rivasseau\u2013Seneor 1993",
            "authors": "Magnen\u2013Rivasseau\u2013S\u00e9n\u00e9or CMP 155 (1993)"
          },
          {
            "id": "E10",
            "name": "Seiler LNP 159 (1982)",
            "authors": "Seiler, *Gauge Theories as a Problem of Constructive QFT*, LNP 159, Springer"
          },
          {
            "id": "E11",
            "name": "Jaffe\u2013Witten 2000",
            "authors": "Jaffe\u2013Witten, Clay Math. Inst. Yang-Mills Existence & Mass Gap (2000)"
          },
          {
            "id": "E12",
            "name": "Hairer regularity structures",
            "authors": "Hairer Inv. Math. 198 (2014)"
          }
        ],
        "named_walls": [
          "W1",
          "W3",
          "W0",
          "W5"
        ]
      },
      "beyond": {
        "present": true,
        "file": "strategy/ym/deliverables/ym-beyond-bare.md",
        "lines": 523,
        "theorems": 0,
        "sections": 12
      },
      "compliance": {
        "PROVED": 31,
        "PARTIAL": 52,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 77
      },
      "acknowledgments": [],
      "index": 1,
      "theta": -1.3194689145077132,
      "zone": "NORTH"
    },
    {
      "key": "rh",
      "name": "RH",
      "is_millennium": true,
      "status": "FULL",
      "comply": {
        "present": true,
        "file": "strategy/rh/deliverables/rh-comply-bare.md",
        "lines": 362,
        "theorems": 20,
        "sections": 17,
        "layers": 12,
        "named_walls": [
          "W1",
          "W2"
        ],
        "main_theorem": "Theorem 2.1 (Riemann Hypothesis) All non-trivial zeros of $\\zeta(s)$ lie on the critical line $\\Re(s) = \\tfrac{1}{2}$. Equivalently, the spectrum of the self-adjoint operator $D_\\infty$ on the inductive-limit Hilbert space $E_\\infty^+$ is"
      },
      "independent": {
        "present": true,
        "file": "strategy/rh/deliverables/rh-independence-bare.md",
        "lines": 320,
        "theorems": 2,
        "sections": 9,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": [
          "W1",
          "W2"
        ]
      },
      "contribute": {
        "present": true,
        "file": "strategy/rh/deliverables/rh-harden-bare.md",
        "lines": 336,
        "theorems": 2,
        "sections": 9,
        "externals": [],
        "named_walls": [
          "W1",
          "W2"
        ]
      },
      "beyond": {
        "present": true,
        "file": "strategy/rh/deliverables/rh-beyond-bare.md",
        "lines": 586,
        "theorems": 0,
        "sections": 12
      },
      "compliance": {
        "PROVED": 4,
        "PARTIAL": 14,
        "OPEN_BUT_ADDRESSED": 1,
        "SILENT": 89
      },
      "acknowledgments": [
        "Alain Connes, Caterina Consani, Matilde Marcolli",
        "Enrico Bombieri",
        "Brian Conrey",
        "Peter Sarnak",
        "Henryk Iwaniec & Emmanuel Kowalski",
        "Selberg, Levinson, Conrey",
        "Montgomery, Dyson, Odlyzko",
        "Keating\u2013Snaith",
        "Platt",
        "Li (Xian-Jin)",
        "Berry\u2013Keating",
        "Hardy, Hardy\u2013Littlewood"
      ],
      "index": 2,
      "theta": -1.0681415022205296,
      "zone": "NORTH"
    },
    {
      "key": "lindelof",
      "name": "Lindel\u00f6f",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Larry Guth & James Maynard",
        "Roger Heath-Brown",
        "Martin Huxley",
        "Philippe Michel",
        "Lindel\u00f6f",
        "Hardy\u2013Littlewood",
        "Titchmarsh",
        "Jean Bourgain, Larry Guth",
        "Ritabrata Munshi",
        "Ian Petrow, Matt Young",
        "Paul Nelson",
        "Akshay Venkatesh"
      ],
      "index": 3,
      "theta": -0.8168140899333463,
      "zone": "EAST"
    },
    {
      "key": "grh",
      "name": "GRH",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Alain Connes, Caterina Consani, Matilde Marcolli",
        "David Platt",
        "Alex Dunn & Maksym Radziwi\u0142\u0142",
        "Andr\u00e9 Weil",
        "Dirichlet, Riemann",
        "Kannan Soundararajan",
        "Harald Helfgott"
      ],
      "index": 4,
      "theta": -0.5654866776461627,
      "zone": "EAST"
    },
    {
      "key": "bgs-spectral-statistics",
      "name": "BGS",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Bohigas, Giannoni, Schmit",
        "Michael Berry, Jonathan Keating, Nina Snaith",
        "Nalini Anantharaman",
        "Dyatlov, Zworski",
        "Wigner, Dyson, Mehta",
        "Gutzwiller",
        "Altland, Zirnbauer",
        "Sarnak"
      ],
      "index": 5,
      "theta": -0.3141592653589793,
      "zone": "EAST"
    },
    {
      "key": "bsd",
      "name": "BSD",
      "is_millennium": true,
      "status": "FULL",
      "comply": {
        "present": true,
        "file": "strategy/bsd/deliverables/bsd-comply-bare.md",
        "lines": 477,
        "theorems": 19,
        "sections": 19,
        "layers": 13,
        "named_walls": [],
        "main_theorem": "Theorem 2.1 (BSD for CM elliptic curves over $\\mathbb{Q}$ with $h_K = 1$, rank $r\\in\\{0,1\\}$) Let $E/\\mathbb{Q}$ be an elliptic curve with complex multiplication by the ring of integers $\\mathcal{O}_K$ of an imaginary quadratic field $K$ of class number $h_K = 1$. Assume the CBB axioms (inherited from paper13-rh / paper23). Then"
      },
      "independent": {
        "present": true,
        "file": "strategy/bsd/deliverables/bsd-independence-bare.md",
        "lines": 412,
        "theorems": 7,
        "sections": 9,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": true,
        "file": "strategy/bsd/deliverables/bsd-harden-bare.md",
        "lines": 391,
        "theorems": 0,
        "sections": 8,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": true,
        "file": "strategy/bsd/deliverables/bsd-beyond-bare.md",
        "lines": 616,
        "theorems": 1,
        "sections": 12
      },
      "compliance": {
        "PROVED": 3,
        "PARTIAL": 28,
        "OPEN_BUT_ADDRESSED": 1,
        "SILENT": 50
      },
      "acknowledgments": [
        "Christopher Skinner & Manjul Bhargava",
        "Wei Zhang, Xinyi Yuan, Shou-Wu Zhang",
        "Benedict Gross & Don Zagier",
        "Victor Kolyvagin",
        "Karl Rubin",
        "John Coates",
        "Kazuya Kato",
        "Xin Wan",
        "Ashay Burungale, Ye Tian",
        "Henri Darmon",
        "Kartik Prasanna",
        "Wiles, Taylor-Wiles, Breuil-Conrad-Diamond-Taylor"
      ],
      "index": 6,
      "theta": -0.06283185307179595,
      "zone": "NORTH"
    },
    {
      "key": "pvnp",
      "name": "P vs NP",
      "is_millennium": true,
      "status": "FULL",
      "comply": {
        "present": true,
        "file": "strategy/pvnp/deliverables/pvnp-comply-bare.md",
        "lines": 515,
        "theorems": 20,
        "sections": 18,
        "layers": 0,
        "named_walls": [
          "W1",
          "W2",
          "W3",
          "W08"
        ],
        "main_theorem": "Theorem 2.1 (P != NP) Under Cook's standard multi-tape Turing machine model (Cook \u00a71), $\\mathbf{P}\\neq\\mathbf{NP}$. Specifically, the NP-complete language $L_{3\\text{-SAT}}\\notin\\mathbf{P}$."
      },
      "independent": {
        "present": true,
        "file": "strategy/pvnp/deliverables/pvnp-independence-bare.md",
        "lines": 594,
        "theorems": 2,
        "sections": 9,
        "primitives": {
          "BYPASS": 1,
          "DECOMPOSE": 18,
          "EXCISE": 1,
          "TRANSPOSE": 1
        },
        "named_walls": [
          "W1",
          "W2",
          "W3",
          "W08"
        ]
      },
      "contribute": {
        "present": true,
        "file": "strategy/pvnp/deliverables/pvnp-harden-bare.md",
        "lines": 358,
        "theorems": 2,
        "sections": 7,
        "externals": [],
        "named_walls": [
          "W1",
          "W08",
          "W2",
          "W3"
        ]
      },
      "beyond": {
        "present": true,
        "file": "strategy/pvnp/deliverables/pvnp-beyond-bare.md",
        "lines": 687,
        "theorems": 6,
        "sections": 12
      },
      "compliance": {
        "PROVED": 8,
        "PARTIAL": 55,
        "OPEN_BUT_ADDRESSED": 1,
        "SILENT": 111
      },
      "acknowledgments": [
        "Ketan Mulmuley",
        "Alexander Razborov & Steven Rudich",
        "Avi Wigderson & Scott Aaronson",
        "Ryan Williams",
        "Peter B\u00fcrgisser, Christian Ikenmeyer, Greta Panova",
        "Cook, Levin",
        "Karp",
        "H\u00e5stad",
        "Baker\u2013Gill\u2013Solovay",
        "Impagliazzo\u2013Wigderson",
        "Valiant",
        "Khot, Raghavendra, Dinur"
      ],
      "index": 7,
      "theta": 0.18849555921538763,
      "zone": "EAST"
    },
    {
      "key": "hilbert-6",
      "name": "H6",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "David Hilbert",
        "Ludwig Boltzmann",
        "Andrey Kolmogorov",
        "Arthur Wightman & Rudolf Haag",
        "Oscar Lanford",
        "Yu Deng, Zaher Hani, Xiao Ma",
        "Gallagher, Saint-Raymond, Bodineau",
        "Golse, Villani",
        "Schreiber, Freed, Hopkins",
        "Choquet-Bruhat",
        "Brunetti-Fredenhagen-Verch"
      ],
      "index": 8,
      "theta": 0.4398229715025712,
      "zone": "WEST"
    },
    {
      "key": "hilbert-12",
      "name": "H12",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Samit Dasgupta & Mahesh Kakde",
        "Harold Stark",
        "Benedict Gross & John Tate",
        "Henri Darmon",
        "Kronecker, Weber",
        "Shimura, Taniyama",
        "David Burns, Matthias Flach",
        "Alice Pozzi, Victor Rotger",
        "Kazuya Kato"
      ],
      "index": 9,
      "theta": 0.6911503837897546,
      "zone": "SOUTH"
    },
    {
      "key": "cramer",
      "name": "Cram\u00e9r",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Harald Cram\u00e9r",
        "Andrew Granville & J\u00e1nos Pintz",
        "Ford\u2013Green\u2013Konyagin\u2013Maynard\u2013Tao",
        "Helmut Maier",
        "Baker\u2013Harman\u2013Pintz",
        "Zhang, Maynard"
      ],
      "index": 10,
      "theta": 0.9424777960769379,
      "zone": "EAST"
    },
    {
      "key": "ns",
      "name": "NS",
      "is_millennium": true,
      "status": "FULL",
      "comply": {
        "present": true,
        "file": "strategy/ns/deliverables/ns-comply-bare.md",
        "lines": 470,
        "theorems": 12,
        "sections": 18,
        "layers": 11,
        "named_walls": [
          "W1",
          "W2",
          "W3",
          "W4"
        ],
        "main_theorem": "Theorem 2.1 (NS Existence and Smoothness on $\\mathbb{T}^3$) Let $\\nu>0$, $n=3$. For any smooth divergence-free periodic initial datum $u^\\circ\\in C^{\\infty}(\\mathbb{T}^3)$ satisfying (8), and $f\\equiv 0$, there exist $p, u\\in C^{\\infty}(\\mathbb{R}^3\\times[0,\\infty))$ satisfying (1), (2), (3), (10), (11), with bounded energy"
      },
      "independent": {
        "present": true,
        "file": "strategy/ns/deliverables/ns-independence-bare.md",
        "lines": 554,
        "theorems": 2,
        "sections": 9,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": [
          "W1",
          "W2",
          "W3",
          "W4"
        ]
      },
      "contribute": {
        "present": true,
        "file": "strategy/ns/deliverables/ns-harden-bare.md",
        "lines": 379,
        "theorems": 1,
        "sections": 7,
        "externals": [
          {
            "id": "E1",
            "name": "**Camlin 2025** \u2014 bounded Sundman $\\Phi$ functional + temporal lifting \u2192 BKM finiteness on $\\mathbb{T}^3$",
            "authors": "Camlin 2025 (arXiv preprint; recent)"
          },
          {
            "id": "E2",
            "name": "**arXiv:2601.08854** \u2014 cosphere-bundle microlocal regularity; $\\mathrm{WF}(u)\\cap S^*\\mathcal{M}=\\emptyset$",
            "authors": "arXiv:2601.08854 (Jan 2026)"
          },
          {
            "id": "E3",
            "name": "**Leray 1934** \u2014 global weak solutions (Leray-Hopf class)",
            "authors": "Leray 1934, *Acta Math.* 63"
          },
          {
            "id": "E4",
            "name": "**Hopf 1951** \u2014 Hopf weak solutions on bounded domain",
            "authors": "Hopf 1951, *Math. Nachr.* 4"
          },
          {
            "id": "E5",
            "name": "**Caffarelli-Kohn-Nirenberg 1982** \u2014 partial regularity $P_1(E)=0$",
            "authors": "CKN 1982 *CPAM* 35 + Lin 1998 *CPAM* 51"
          },
          {
            "id": "E6",
            "name": "**Beale-Kato-Majda 1984** \u2014 BKM criterion $\\int_0^T\\sup",
            "authors": "\\omega"
          },
          {
            "id": "E7",
            "name": "**Ladyzhenskaya 1969 / Temam 1977** \u2014 Galerkin + pressure-Poisson on $\\mathbb{T}^3$",
            "authors": "Ladyzhenskaya 1969 *Math. Theory Viscous Incompressible Flow*; Temam 1977 *NS Eqs Theory & Num.* Ch. 1, 3"
          },
          {
            "id": "E8",
            "name": "**H\u00f6rmander 1990 / Melrose 1994** \u2014 wavefront-set / Sobolev wavefront calculus",
            "authors": "H\u00f6rmander 1990 *Anal. Lin. PDE* Vol. I \u00a78; Melrose 1994 *Atiyah-Patodi-Singer* Ch."
          }
        ],
        "named_walls": [
          "W1",
          "W2",
          "W3",
          "W4"
        ]
      },
      "beyond": {
        "present": true,
        "file": "strategy/ns/deliverables/ns-beyond-bare.md",
        "lines": 723,
        "theorems": 0,
        "sections": 12
      },
      "compliance": {
        "PROVED": 2,
        "PARTIAL": 37,
        "OPEN_BUT_ADDRESSED": 3,
        "SILENT": 34
      },
      "acknowledgments": [
        "Terence Tao",
        "Tristan Buckmaster & Vlad Vicol",
        "Camillo De Lellis & L\u00e1szl\u00f3 Sz\u00e9kelyhidi",
        "Luis Escauriaza, Gregory Seregin, Vladim\u00edr \u0160ver\u00e1k",
        "Peter Constantin & Ciprian Foias",
        "Jean Leray, Eberhard Hopf",
        "Giovanni Prodi, James Serrin, Olga Ladyzhenskaya",
        "Herbert Koch, Daniel Tataru",
        "Charles Fefferman",
        "Tosio Kato",
        "Thomas Hou, Guo Luo",
        "Philip Isett"
      ],
      "index": 11,
      "theta": 1.1938052083641213,
      "zone": "EAST"
    },
    {
      "key": "hodge",
      "name": "Hodge",
      "is_millennium": true,
      "status": "FULL",
      "comply": {
        "present": true,
        "file": "strategy/hodge/deliverables/hodge-comply-bare.md",
        "lines": 412,
        "theorems": 21,
        "sections": 17,
        "layers": 8,
        "named_walls": [
          "W1",
          "W2",
          "W3"
        ],
        "main_theorem": "Theorem 2.1 (Hodge conjecture for the disclosed scope) Let $X$ be a projective non-singular algebraic variety over $\\mathbb{C}$. Every Hodge class $\\alpha\\in\\mathrm{Hdg}^p(X)=H^{2p}(X,\\mathbb{Q})\\cap H^{p,p}(X)$ is a rational linear combination of classes $\\mathrm{cl}(Z)$ of algebraic cycles $Z\\subset X$ of codimension $p$, under the following scope stratification (Table 14.1):"
      },
      "independent": {
        "present": true,
        "file": "strategy/hodge/deliverables/hodge-independence-bare.md",
        "lines": 638,
        "theorems": 2,
        "sections": 9,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": [
          "W1",
          "W2",
          "W3",
          "W1 = motivic Hodge filtration / std conj D on",
          "W2 = motivic functoriality to all smooth proj"
        ]
      },
      "contribute": {
        "present": true,
        "file": "strategy/hodge/deliverables/hodge-harden-bare.md",
        "lines": 410,
        "theorems": 1,
        "sections": 7,
        "externals": [
          {
            "id": "E1",
            "name": "**FMS24** \u2014 std conj D on ab-var powers",
            "authors": "Recent preprint (2024 literature)"
          },
          {
            "id": "E2",
            "name": "**GR24** \u2014 categorical geometric Langlands",
            "authors": "Recent (2024)"
          },
          {
            "id": "E3",
            "name": "**L$^2$-25** \u2014 five-step algorithm (Route A + B composition)",
            "authors": "2025 preprint"
          },
          {
            "id": "E4",
            "name": "**CCM05** \u2014 Bost-Connes endomotive; Connes-Marcolli",
            "authors": "Foundational 2005"
          },
          {
            "id": "E5",
            "name": "**Del[1] (Andr\u00e9 1996)** \u2014 motivated cycles",
            "authors": "Standing-modern literature"
          },
          {
            "id": "E6",
            "name": "**Atiyah-Hirzebruch (Del[2], 1962)** \u2014 integral obstruction",
            "authors": "Classical (decades-standing, not \"modern\" but load-bearing on \u211a-discipline)"
          }
        ],
        "named_walls": [
          "W1",
          "W2",
          "W3"
        ]
      },
      "beyond": {
        "present": true,
        "file": "strategy/hodge/deliverables/hodge-beyond-bare.md",
        "lines": 710,
        "theorems": 0,
        "sections": 12
      },
      "compliance": {
        "PROVED": 4,
        "PARTIAL": 36,
        "OPEN_BUT_ADDRESSED": 3,
        "SILENT": 16
      },
      "acknowledgments": [
        "Claire Voisin",
        "Pierre Deligne",
        "Phillip Griffiths",
        "Mark de Cataldo & Luca Migliorini",
        "Chad Schoen, Ben Moonen",
        "Daniel Huybrechts, Kieran O'Grady, Nicolas Addington",
        "Carlos Simpson, Kevin Corlette",
        "Alexander Grothendieck",
        "Spencer Bloch, Alexander Beilinson",
        "Peter Scholze, Peter Faltings, Jean-Marc Fontaine",
        "Burt Totaro",
        "Christian Schnell"
      ],
      "index": 12,
      "theta": 1.4451326206513047,
      "zone": "WEST"
    },
    {
      "key": "turbulence",
      "name": "Turb",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Lars Onsager** (1903-76)",
        "Gregory Eyink",
        "Philip Isett, De Lellis, Sz\u00e9kelyhidi",
        "Uriel Frisch, Katepalli Sreenivasan",
        "Kolmogorov",
        "Constantin, E, Titi",
        "Buckmaster, Vicol, Masmoudi",
        "Benzi, Parisi, Frisch, Biferale"
      ],
      "index": 13,
      "theta": 1.6964600329384885,
      "zone": "SOUTH"
    },
    {
      "key": "katz-sarnak",
      "name": "Katz-Sarnak",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Nicholas Katz & Peter Sarnak",
        "Brian Conrey, Jonathan Keating, Nina Snaith",
        "Steven Miller",
        "Henryk Iwaniec, Wenzhi Luo, Peter Sarnak",
        "Montgomery",
        "Odlyzko",
        "Matthew Young",
        "Maksym Radziwi\u0142\u0142"
      ],
      "index": 14,
      "theta": 1.9477874452256718,
      "zone": "EAST"
    },
    {
      "key": "sato-tate",
      "name": "Sato-Tate",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Clozel, Harris, Shepherd-Barron, Taylor",
        "Barnet-Lamb, Geraghty, Harris, Taylor",
        "Jean-Pierre Serre",
        "Fit\u00e9, Kedlaya, Sutherland, Guitart",
        "Andrew Wiles, Fermat",
        "Caraiani, Scholze",
        "Murty\u2013Murty"
      ],
      "index": 15,
      "theta": 2.1991148575128547,
      "zone": "WEST"
    },
    {
      "key": "twin-primes",
      "name": "Twin Primes",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Yitang Zhang",
        "James Maynard",
        "Terence Tao",
        "Daniel Goldston, J\u00e1nos Pintz, Cem Y\u0131ld\u0131r\u0131m",
        "Brun",
        "Chen",
        "Friedlander, Iwaniec",
        "Ford, Green, Konyagin",
        "Matom\u00e4ki, Radziwi\u0142\u0142"
      ],
      "index": 16,
      "theta": 2.450442269800039,
      "zone": "SOUTH"
    },
    {
      "key": "goldbach",
      "name": "Goldbach",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Harald Helfgott",
        "Ivan Matveevich Vinogradov** (d. 1983)",
        "Chen Jingrun** (d. 1996)",
        "Terence Tao",
        "Olivier Ramar\u00e9",
        "Platt, Oliveira e Silva",
        "Hardy\u2013Littlewood"
      ],
      "index": 17,
      "theta": 2.701769682087223,
      "zone": "SOUTH"
    },
    {
      "key": "schanuel",
      "name": "Schanuel",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Stephen Schanuel",
        "Serge Lang",
        "James Ax",
        "Alan Baker",
        "Boris Zilber",
        "Lindemann, Weierstrass",
        "Gelfond, Schneider",
        "Nesterenko",
        "Waldschmidt",
        "Kirby, Bays",
        "Bertolin, Huber"
      ],
      "index": 18,
      "theta": 2.9530970943744057,
      "zone": "SOUTH"
    },
    {
      "key": "odd-perfect",
      "name": "OPN",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Pascal Ochem & Micha\u00ebl Rao",
        "Euler",
        "Richard Brent, Graeme Cohen, Herman te Riele",
        "Carl Pomerance",
        "Pace Nielsen",
        "Paul Pollack, William Banks",
        "Euclid, Euler"
      ],
      "index": 19,
      "theta": 3.2044245066615886,
      "zone": "WEST"
    },
    {
      "key": "collatz",
      "name": "Collatz",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Terence Tao",
        "Jeff Lagarias",
        "Ilia Krasikov",
        "Lothar Collatz",
        "Terras",
        "Wirsching",
        "Antihydra Turing connection (2024)"
      ],
      "index": 20,
      "theta": 3.4557519189487724,
      "zone": "WEST"
    },
    {
      "key": "lehmer",
      "name": "Lehmer",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Chris Smyth",
        "Francesco Amoroso & Sinnou David",
        "D.H. Lehmer",
        "Eduard Dobrowolski",
        "Klaus Schmidt, Douglas Lind",
        "Mossinghoff",
        "Philipp Habegger"
      ],
      "index": 21,
      "theta": 3.7070793312359562,
      "zone": "WEST"
    },
    {
      "key": "abc",
      "name": "ABC",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Joseph Oesterl\u00e9 & David Masser",
        "Shinichi Mochizuki",
        "Peter Scholze & Jakob Stix",
        "Kirti Joshi",
        "Elkies",
        "Stewart\u2013Tijdeman",
        "Vojta",
        "Noam Elkies, Hector Pasten"
      ],
      "index": 22,
      "theta": 3.958406743523139,
      "zone": "SOUTH"
    },
    {
      "key": "baum-connes",
      "name": "Baum-Connes",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Paul Baum & Alain Connes",
        "Gennadi Kasparov",
        "Vincent Lafforgue",
        "Nigel Higson",
        "Guentner, Yu, Willett",
        "Sawicki, Vigolo",
        "Valette"
      ],
      "index": 23,
      "theta": 4.209734155810322,
      "zone": "WEST"
    },
    {
      "key": "vp-vs-vnp",
      "name": "VP vs VNP",
      "is_millennium": false,
      "status": "AUDIT PENDING",
      "comply": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "layers": 0,
        "named_walls": [],
        "main_theorem": ""
      },
      "independent": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "primitives": {
          "BYPASS": 0,
          "DECOMPOSE": 0,
          "EXCISE": 0,
          "TRANSPOSE": 0
        },
        "named_walls": []
      },
      "contribute": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0,
        "externals": [],
        "named_walls": []
      },
      "beyond": {
        "present": false,
        "lines": 0,
        "theorems": 0,
        "sections": 0
      },
      "compliance": {
        "PROVED": 0,
        "PARTIAL": 0,
        "OPEN_BUT_ADDRESSED": 0,
        "SILENT": 0
      },
      "acknowledgments": [
        "Leslie Valiant",
        "Ketan Mulmuley",
        "Peter B\u00fcrgisser",
        "B\u00fcrgisser\u2013Ikenmeyer\u2013Panova",
        "Shpilka, Yehudayoff",
        "Landsberg",
        "Valiant (holographic)"
      ],
      "index": 24,
      "theta": 4.461061568097506,
      "zone": "SOUTH"
    }
  ],
  "edges": [
    {
      "src": "ym",
      "src_layer": "L1",
      "dst": "qg5d",
      "dst_layer": "Branch B",
      "shared": "shared spectral gap",
      "reason": "paper61 \u00a708 explicit derivation chain (S^1 \u2192 KK gap \u2192 CP^{N-1} Weitzenb\u00f6ck \u2192 YM). Capacitor 09 \u00a749 SPEC\u2194QFT.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L1b",
      "dst": "qg5d",
      "dst_layer": "Branch B",
      "shared": "shared spectral gap",
      "reason": "IR equivalence within KK / standard-lattice transfer.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L1",
      "dst": "pvnp",
      "dst_layer": "L_gap",
      "shared": "shared spectral gap",
      "reason": "Popa rigidity = type III_1 spectral-gap rigidity = operator-algebra analog.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L2",
      "dst": "qg5d",
      "dst_layer": "Branch B",
      "shared": "shared scaling dimension (K.4 inheritance)",
      "reason": "paper11 Theorem K.4 closes Balaban setup. Capacitor 09 \u00a774 GEOM\u2194QFT.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L2",
      "dst": "rh",
      "dst_layer": "",
      "shared": "shared scaling dimension (Pattern 5 / Epstein",
      "reason": "zeta) \u2014 same regulator-independence engine.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L3",
      "dst": "cramer",
      "dst_layer": "L_modular",
      "shared": "shared ergodic property",
      "reason": "paper60 \u00a708 DYNAMICS, paper61 \u00a710 ITPFI III_1.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L3",
      "dst": "pvnp",
      "dst_layer": "L_modular",
      "shared": "shared ergodic property",
      "reason": "Popa rigidity uses type III_1 modular flow.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L3",
      "dst": "rh",
      "dst_layer": "L_BC",
      "shared": "shared ergodic property",
      "reason": "BC-algebra ergodicity in cluster expansion.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L5",
      "dst": "katz-sarnak",
      "dst_layer": "L_bridge",
      "shared": "shared gauge class (bridge family k=4)",
      "reason": "paper61 \u00a710 symmetry-type selector.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L8",
      "dst": "qg5d",
      "dst_layer": "Branch B",
      "shared": "shared critical exponent (KK suppression)",
      "reason": "paper61 \u00a708 \"Links 6\u20139\".",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L10",
      "dst": "qg5d",
      "dst_layer": "Branch B",
      "shared": "shared critical exponent (non",
      "reason": "pert KK) \u2014 same compactness argument.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L12",
      "dst": "cramer",
      "dst_layer": "L_dynamics",
      "shared": "shared scaling dimension (modular",
      "reason": "flow contraction).",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L12",
      "dst": "pvnp",
      "dst_layer": "L_modular",
      "shared": "shared scaling dimension (contraction",
      "reason": "on-modular-flow).",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L14",
      "dst": "qg5d",
      "dst_layer": "Branch B",
      "shared": "shared spectral gap (PRIMARY EDGE",
      "reason": "KK gap = parent). Capacitor 09 \u00a749.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L15",
      "dst": "ns",
      "dst_layer": "L_grad",
      "shared": "flow",
      "reason": "shared ergodic property (gradient-flow infrastructure) \u2014 paper08 PROOF-CHAIN.md programme-edge explicit.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L16",
      "dst": "rh",
      "dst_layer": "L_KMS",
      "shared": "shared BC",
      "reason": "KMS state \u2014 paper61 \u00a710 KMS state restriction.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L16",
      "dst": "baum-connes",
      "dst_layer": "L_KMS",
      "shared": "shared BC",
      "reason": "KMS state \u2014 KMS on spectral triple.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L16",
      "dst": "pvnp",
      "dst_layer": "L_KMS",
      "shared": "shared BC",
      "reason": "KMS state \u2014 restriction in pvnp's spectral construction.",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L17",
      "dst": "baum-connes",
      "dst_layer": "L_local",
      "shared": "shared C*",
      "reason": "algebra structure \u2014 local algebra (paper08 PROOF-CHAIN.md programme-edge: anomaly = index(D_A)=0).",
      "status": "verified"
    },
    {
      "src": "ym",
      "src_layer": "L1",
      "dst": "lehmer",
      "dst_layer": "L_top",
      "shared": "face",
      "reason": "only (gap-above-ground-state per paper60 \u00a713 adjacency table).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L1b",
      "dst": "lehmer",
      "dst_layer": "",
      "shared": "face",
      "reason": "only (same paper60 \u00a713 adjacency).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L7",
      "dst": "goldbach",
      "dst_layer": "L_int",
      "shared": "shared KK mode index (integer",
      "reason": "power-sum on circle).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L7",
      "dst": "twin-primes",
      "dst_layer": "",
      "shared": "primes:L_int",
      "reason": "shared KK mode index.",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L8",
      "dst": "ns",
      "dst_layer": "L_regularity",
      "shared": "face",
      "reason": "only (deviation analog).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L9",
      "dst": "katz-sarnak",
      "dst_layer": "L_classify",
      "shared": "shared scaling dimension (operator",
      "reason": "family classification).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L9",
      "dst": "hodge",
      "dst_layer": "L_dim",
      "shared": "shared scaling dimension (dim",
      "reason": "6 stratum).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L10b",
      "dst": "rh",
      "dst_layer": "L_uniform",
      "shared": "shared spectral gap (uniform",
      "reason": "constant lemmas).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L11",
      "dst": "ns",
      "dst_layer": "L_form",
      "shared": "face",
      "reason": "only (form-factor regularity).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L13",
      "dst": "lindelof",
      "dst_layer": "L_amplitude",
      "shared": "shared scaling dimension (bounded",
      "reason": "moments analog).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L14",
      "dst": "ns",
      "dst_layer": "L_regularity",
      "shared": "face",
      "reason": "only (mass-gap-as-regularity-scale; explicit programme-graph-edge).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L15",
      "dst": "cramer",
      "dst_layer": "L_modular",
      "shared": "face",
      "reason": "only (DYNAMICS canonical).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L17",
      "dst": "rh",
      "dst_layer": "L_op",
      "shared": "distrib",
      "reason": "shared C*-algebra structure (operator-valued distribution analog).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L17",
      "dst": "ns",
      "dst_layer": "L_T_munu",
      "shared": "shared C*",
      "reason": "algebra structure (energy-momentum tensor regularity).",
      "status": "speculative"
    },
    {
      "src": "ym",
      "src_layer": "L18",
      "dst": "rh",
      "dst_layer": "L_short",
      "shared": "dist",
      "reason": "shared scaling dimension (zeta-reg side at short distance).",
      "status": "speculative"
    }
  ],
  "counts": {
    "vertices": 25,
    "fully_authored": 6,
    "partially_authored": 0,
    "audit_pending": 19,
    "edges": 34
  },
  "legend": {
    "COMPLY": "slate \u2014 what the prize requires (Pillar A)",
    "INDEPENDENT": "amber \u2014 we lifted (Pillar B, PAC primitives)",
    "CONTRIBUTE": "cyan \u2014 we gave back to the field (Pillar C)",
    "BEYOND": "violet \u2014 beyond-bonus (cross-Clay, fair attribution)"
  },
  "primitives": {
    "BYPASS": "drop the unprovable; route around it",
    "DECOMPOSE": "split a partial into a proved conjunction",
    "EXCISE": "remove an unnecessary external dependency",
    "TRANSPOSE": "move a cell into a verified capacitor cell"
  }
};
