// Atlas cross-cut edges — aggregated from all 25 X-RAY.md files + qg5d hub.
// Generated 2026-04-15 from strategy/x-ray/proof-chain/*/X-RAY.md §4/§7 enumerations.
// Format: [{from, to, shared}]
// Edge orientation is alphabetical-low→alphabetical-high; (A,B) == (B,A) in the chord graph.

// Stats: 849 unique edges across 25 vertices.

const ATLAS_EDGES = [
  {from:"abc", to:"baum-connes", shared:"C*-algebra structure (Cuntz-Li semigroup)"},
  {from:"abc", to:"baum-connes", shared:"ITPFI factor type"},
  {from:"abc", to:"bgs", shared:"C*-algebra structure (BC at KMS$_1$ → type III$_1$)"},
  {from:"abc", to:"bgs", shared:"spectral gap (sine-kernel universality output)"},
  {from:"abc", to:"bgs", shared:"zero distribution (GUE sine-kernel)"},
  {from:"abc", to:"bsd", shared:"BC-KMS state (parallel BC-partition-derived height)"},
  {from:"abc", to:"bsd", shared:"C*-algebra structure (BC over $K$ extension)"},
  {from:"abc", to:"bsd", shared:"C*-algebra structure (number-field ITPFI extension)"},
  {from:"abc", to:"bsd", shared:"L-value / C*-algebra structure (Szpiro ≡ ABC)"},
  {from:"abc", to:"collatz", shared:"scaling dimension (HARMONICS canonical)"},
  {from:"abc", to:"cramer", shared:"zero distribution (GUE three-tail)"},
  {from:"abc", to:"goldbach", shared:"BC-KMS state (novel KMS$_1$-derived closure)"},
  {from:"abc", to:"goldbach", shared:"BC-KMS state (parallel novel KMS$_1$-derived conjecture)"},
  {from:"abc", to:"goldbach", shared:"C*-algebra structure"},
  {from:"abc", to:"goldbach", shared:"ITPFI factor type (unique factorization)"},
  {from:"abc", to:"goldbach", shared:"scaling dimension (south-trough wall)"},
  {from:"abc", to:"goldbach", shared:"spectral gap / scaling dimension (Mellin bridge)"},
  {from:"abc", to:"grh", shared:"zero distribution (GRH → improved abc-triple bounds)"},
  {from:"abc", to:"grh", shared:"zero distribution (generalized zeros for multi-modulus ABC)"},
  {from:"abc", to:"lindelof", shared:"face-only (bounded ζ moments)"},
  {from:"abc", to:"opn", shared:"ARITHMETIC face (rad$(n)$ bound)"},
  {from:"abc", to:"pvnp", shared:"C*-algebra structure"},
  {from:"abc", to:"qg5d", shared:"C*-algebra structure + BC-KMS state"},
  {from:"abc", to:"qg5d", shared:"scaling dimension (radical height), gauge class (tame ramification)"},
  {from:"abc", to:"rh", shared:"BC-KMS state"},
  {from:"abc", to:"rh", shared:"C*-algebra structure (BC-algebra Hecke generation)"},
  {from:"abc", to:"rh", shared:"C*-algebra structure (Euler product as ITPFI)"},
  {from:"abc", to:"rh", shared:"L-value (zero-free region bounds)"},
  {from:"abc", to:"rh", shared:"spectral gap (explicit formula)"},
  {from:"abc", to:"rh", shared:"zero distribution"},
  {from:"abc", to:"schanuel", shared:"Galois representation / ARITHMETIC South adjacency"},
  {from:"abc", to:"schanuel", shared:"TOPOLOGY / ARITHMETIC adjacency on south trough"},
  {from:"abc", to:"schanuel", shared:"face-only (transcendence of $K(\\varepsilon)$)"},
  {from:"abc", to:"schanuel", shared:"face-only (transcendence of $L$-value arguments in $K(\\varepsilon)$)"},
  {from:"abc", to:"schanuel", shared:"face-only speculative (transcendence of $L$-value at bridge arguments)"},
  {from:"abc", to:"schanuel", shared:"face-only speculative (transcendence of height values)"},
  {from:"abc", to:"twin-primes", shared:"BC-KMS state (parallel arithmetic-fine-structure conjecture)"},
  {from:"abc", to:"twin-primes", shared:"C*-algebra structure"},
  {from:"abc", to:"twin-primes", shared:"ITPFI factor type (arithmetic factor from BC)"},
  {from:"abc", to:"twin-primes", shared:"L-value (asymptotic constant)"},
  {from:"abc", to:"twin-primes", shared:"face-only (diophantine additive-multiplicative interface)"},
  {from:"abc", to:"twin-primes", shared:"spectral gap (explicit formula as Mellin bridge)"},
  {from:"abc", to:"twin-primes", shared:"zero distribution (GUE fine structure)"},
  {from:"abc", to:"vp-vs-vnp", shared:"face-only speculative (effective counting bounds)"},
  {from:"baum-connes", to:"bgs", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"bgs", shared:"C*-algebra structure, ITPFI factor type"},
  {from:"baum-connes", to:"bgs", shared:"ITPFI factor type"},
  {from:"baum-connes", to:"bgs", shared:"spectral gap"},
  {from:"baum-connes", to:"bsd", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"collatz", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"collatz", shared:"C*-algebra structure (Cuntz-algebra sub-inclusion)"},
  {from:"baum-connes", to:"collatz", shared:"ITPFI factor type"},
  {from:"baum-connes", to:"cramer", shared:"BC-KMS state"},
  {from:"baum-connes", to:"goldbach", shared:"$\\mathbb{N}^\\rtimes$ (Cuntz-Li semigroup)"},
  {from:"baum-connes", to:"goldbach", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"goldbach", shared:"C*-algebra structure (Cuntz-Li semigroup)"},
  {from:"baum-connes", to:"goldbach", shared:"C*-algebra structure, KK mode index"},
  {from:"baum-connes", to:"goldbach", shared:"structural analog at K-theory pairing"},
  {from:"baum-connes", to:"grh", shared:"BC-KMS state"},
  {from:"baum-connes", to:"grh", shared:"spectral-triple structure"},
  {from:"baum-connes", to:"h12", shared:"C*-algebra structure (K-theory of BC algebra)"},
  {from:"baum-connes", to:"h12", shared:"holonomy (profinite $\\mathbb{Q}/\\mathbb{Z}$ torsion)"},
  {from:"baum-connes", to:"hilbert-6", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"hilbert-6", shared:"C*-algebra structure (Wightman recovery)"},
  {from:"baum-connes", to:"hilbert-6", shared:"gauge class"},
  {from:"baum-connes", to:"hodge", shared:"BC C*-algebra shared foundation; paper29 programme-graph-edge"},
  {from:"baum-connes", to:"hodge", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"hodge", shared:"Chern-character isomorphism K-theory ↔ rational cohomology — Chern class of hype"},
  {from:"baum-connes", to:"hodge", shared:"K-theoretic functoriality analog — assembly-map closure"},
  {from:"baum-connes", to:"hodge", shared:"K-theory ↔ Chow-group identification via Chern character; paper29 programme-grap"},
  {from:"baum-connes", to:"hodge", shared:"K-theory-category reconstruction analog"},
  {from:"baum-connes", to:"hodge", shared:"categorical / K-theoretic equivalence analog; paper29 programme-graph-edge"},
  {from:"baum-connes", to:"hodge", shared:"face-only (TOPOLOGY, classifying space for vector bundles)"},
  {from:"baum-connes", to:"lehmer", shared:"BC-KMS state (KMS state on spectral triple)"},
  {from:"baum-connes", to:"lehmer", shared:"Galois representation (l-adic cohomology pairing)"},
  {from:"baum-connes", to:"lindelof", shared:"BC-KMS state"},
  {from:"baum-connes", to:"ns", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"ns", shared:"face-only (K-theoretic rigidity)"},
  {from:"baum-connes", to:"ns", shared:"scaling dimension"},
  {from:"baum-connes", to:"ns", shared:"spectral gap"},
  {from:"baum-connes", to:"opn", shared:"C*-algebra structure (Cuntz-Li semigroup)"},
  {from:"baum-connes", to:"pvnp", shared:"BC-KMS state (spectral triple)"},
  {from:"baum-connes", to:"pvnp", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"pvnp", shared:"C*-algebra structure (amenability / non-fullness analog)"},
  {from:"baum-connes", to:"pvnp", shared:"C\\*-algebra structure"},
  {from:"baum-connes", to:"pvnp", shared:"C\\*-algebra structure (Feldman-Moore K-theory)"},
  {from:"baum-connes", to:"pvnp", shared:"C\\*-algebra structure (groupoid K-theory)"},
  {from:"baum-connes", to:"pvnp", shared:"C\\*-algebra structure (non-amenable groupoid K-theory)"},
  {from:"baum-connes", to:"qg5d", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"qg5d", shared:"C*-algebra structure, BC-KMS state"},
  {from:"baum-connes", to:"qg5d", shared:"C*-algebra structure, BC-KMS state, ITPFI factor type"},
  {from:"baum-connes", to:"qg5d", shared:"C*-algebra structure, KK mode index"},
  {from:"baum-connes", to:"qg5d", shared:"spectral gap, C*-algebra structure"},
  {from:"baum-connes", to:"rh", shared:"BC-KMS state"},
  {from:"baum-connes", to:"rh", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"rh", shared:"ITPFI factor type"},
  {from:"baum-connes", to:"rh", shared:"spectral gap, BC-KMS state"},
  {from:"baum-connes", to:"rh", shared:"spectral gap, C*-algebra structure"},
  {from:"baum-connes", to:"sato-tate", shared:"BC-KMS state (K-theory of spectral triple)"},
  {from:"baum-connes", to:"schanuel", shared:"spectral triple"},
  {from:"baum-connes", to:"turbulence", shared:"ITPFI factor type"},
  {from:"baum-connes", to:"turbulence", shared:"L-value"},
  {from:"baum-connes", to:"turbulence", shared:"scaling dimension"},
  {from:"baum-connes", to:"turbulence", shared:"spectral gap"},
  {from:"baum-connes", to:"twin-primes", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"vp-vs-vnp", shared:"C*-algebra structure (K-theoretic / operator-algebra translation dictionary)"},
  {from:"baum-connes", to:"vp-vs-vnp", shared:"C*-algebra structure (K-theory of continuous BC)"},
  {from:"baum-connes", to:"vp-vs-vnp", shared:"C*-algebra structure (assembly-map closure)"},
  {from:"baum-connes", to:"ym", shared:"BC-KMS state"},
  {from:"baum-connes", to:"ym", shared:"C*-algebra structure"},
  {from:"baum-connes", to:"ym", shared:"C*-algebra structure (anomaly = K-theory pairing)"},
  {from:"bgs", to:"bsd", shared:"zero distribution / Galois representation"},
  {from:"bgs", to:"collatz", shared:"BC-KMS state"},
  {from:"bgs", to:"collatz", shared:"ITPFI factor type (modular-flow ergodicity → no periodic orbits)"},
  {from:"bgs", to:"collatz", shared:"ergodic property (entropy bound)"},
  {from:"bgs", to:"collatz", shared:"ergodic property (type III$_1$ modular flow)"},
  {from:"bgs", to:"cramer", shared:"ITPFI factor type (type III$_1$, $\\lambda_p = 1/p$)"},
  {from:"bgs", to:"cramer", shared:"L-value (sine kernel indirect error control)"},
  {from:"bgs", to:"cramer", shared:"ergodic property"},
  {from:"bgs", to:"cramer", shared:"ergodic property (universality-class tail)"},
  {from:"bgs", to:"cramer", shared:"ergodic property + BC-KMS state (DIRECT structural input)"},
  {from:"bgs", to:"cramer", shared:"ergodic property + ITPFI factor type"},
  {from:"bgs", to:"cramer", shared:"face-only (both CCM-gated outer-ring closures)"},
  {from:"bgs", to:"cramer", shared:"zero distribution"},
  {from:"bgs", to:"cramer", shared:"zero distribution (Dyson unitary class)"},
  {from:"bgs", to:"cramer", shared:"zero distribution (GUE extreme-value tail)"},
  {from:"bgs", to:"cramer", shared:"zero distribution (GUE prime-gap numerics)"},
  {from:"bgs", to:"goldbach", shared:"C*-algebra structure (BC at KMS$_1$)"},
  {from:"bgs", to:"goldbach", shared:"Mellin bridge output (sine-kernel universality)"},
  {from:"bgs", to:"goldbach", shared:"bulk-regime delivery"},
  {from:"bgs", to:"goldbach", shared:"bulk-regime sine-kernel + GUE three-tail"},
  {from:"bgs", to:"goldbach", shared:"zero distribution + sine-kernel universality"},
  {from:"bgs", to:"grh", shared:"ITPFI factor structure"},
  {from:"bgs", to:"grh", shared:"zero distribution (GUE pair correlation of zeros)"},
  {from:"bgs", to:"h12", shared:"BC-KMS state"},
  {from:"bgs", to:"h12", shared:"BC-KMS state (ergodic / broken-ergodic pairing)"},
  {from:"bgs", to:"hilbert-6", shared:"BC-KMS state (pin-level)"},
  {from:"bgs", to:"hodge", shared:"C*-algebra structure (parity engine analog)"},
  {from:"bgs", to:"katz-sarnak", shared:"C*-algebra structure (Dyson threefold way)"},
  {from:"bgs", to:"katz-sarnak", shared:"Galois representation (Dyson threefold way = K-S classification)"},
  {from:"bgs", to:"katz-sarnak", shared:"Galois representation (unitary bridge $k=3$)"},
  {from:"bgs", to:"katz-sarnak", shared:"L-value (GUE moments)"},
  {from:"bgs", to:"katz-sarnak", shared:"zero distribution (GUE at $U$-type)"},
  {from:"bgs", to:"katz-sarnak", shared:"zero distribution (GUE is $U$-slice of Deligne)"},
  {from:"bgs", to:"katz-sarnak", shared:"zero distribution (symmetry-type numerical verification)"},
  {from:"bgs", to:"katz-sarnak", shared:"zero distribution (unitary universality)"},
  {from:"bgs", to:"lehmer", shared:"BC-KMS state (modular flow ergodicity at $\\beta = 1$)"},
  {from:"bgs", to:"lindelof", shared:"ITPFI factor type, BC-KMS state"},
  {from:"bgs", to:"lindelof", shared:"amplitude statistics"},
  {from:"bgs", to:"lindelof", shared:"scaling dimension"},
  {from:"bgs", to:"lindelof", shared:"zero distribution (GUE moments $T(\\log T)^{k^2}$)"},
  {from:"bgs", to:"lindelof", shared:"zero distribution (large-scale moment numerics)"},
  {from:"bgs", to:"ns", shared:"ergodic property"},
  {from:"bgs", to:"opn", shared:"ITPFI factor type"},
  {from:"bgs", to:"opn", shared:"ITPFI factor type (BC at KMS$_1$)"},
  {from:"bgs", to:"pvnp", shared:"Galois representation (CCM gate)"},
  {from:"bgs", to:"pvnp", shared:"ITPFI factor type"},
  {from:"bgs", to:"pvnp", shared:"ergodic property"},
  {from:"bgs", to:"pvnp", shared:"zero distribution (channel-correspondence universality)"},
  {from:"bgs", to:"qg5d", shared:"ITPFI factor type (type III$_1$)"},
  {from:"bgs", to:"qg5d", shared:"KK mode index (Branch E contact)"},
  {from:"bgs", to:"qg5d", shared:"ergodic property, BC-KMS state"},
  {from:"bgs", to:"qg5d", shared:"zero distribution (spec($H_R$) = {γ$_n \\pi^2/2$})"},
  {from:"bgs", to:"rh", shared:"C*-algebra structure (unitary symmetry-class)"},
  {from:"bgs", to:"rh", shared:"ITPFI factor type / C*-algebra structure"},
  {from:"bgs", to:"rh", shared:"ergodic property"},
  {from:"bgs", to:"rh", shared:"ergodic property (BC-algebra resolvent)"},
  {from:"bgs", to:"rh", shared:"holonomy (linking number = pair correlation statistic)"},
  {from:"bgs", to:"rh", shared:"scaling dimension (ζ(1+it) decay)"},
  {from:"bgs", to:"rh", shared:"spectral gap"},
  {from:"bgs", to:"rh", shared:"zero distribution (pair-correlation conjecture)"},
  {from:"bgs", to:"rh", shared:"zero distribution / Galois representation (spec($D_\\infty$) = {γ$_n$}, PRIMARY CCM-GATE EDGE)"},
  {from:"bgs", to:"sato-tate", shared:"BC-KMS state / ITPFI factor type (type III$_1$)"},
  {from:"bgs", to:"sato-tate", shared:"C*-algebra structure"},
  {from:"bgs", to:"sato-tate", shared:"C*-algebra structure (Haar on unitary group)"},
  {from:"bgs", to:"sato-tate", shared:"C*-algebra structure (Hecke asymmetry)"},
  {from:"bgs", to:"sato-tate", shared:"Galois representation (Frobenius angles to zero statistics via Haar)"},
  {from:"bgs", to:"sato-tate", shared:"zero distribution (CCM-gated spectral closure)"},
  {from:"bgs", to:"sato-tate", shared:"zero distribution (CCM-gated spectral identification)"},
  {from:"bgs", to:"sato-tate", shared:"zero distribution (Haar pushforward)"},
  {from:"bgs", to:"sato-tate", shared:"zero distribution (equidistribution numerics)"},
  {from:"bgs", to:"schanuel", shared:"scaling dimension"},
  {from:"bgs", to:"schanuel", shared:"zero distribution"},
  {from:"bgs", to:"turbulence", shared:"ITPFI factor type (III$_1$)"},
  {from:"bgs", to:"turbulence", shared:"L-value"},
  {from:"bgs", to:"turbulence", shared:"ergodic property"},
  {from:"bgs", to:"turbulence", shared:"ergodic property (GUE kernel)"},
  {from:"bgs", to:"twin-primes", shared:"**PRIMARY EDGE**"},
  {from:"bgs", to:"twin-primes", shared:"C*-algebra structure (Hecke asymmetry)"},
  {from:"bgs", to:"twin-primes", shared:"ergodic property (GUE small-gap universality)"},
  {from:"bgs", to:"twin-primes", shared:"zero distribution (GUE small-gap tail)"},
  {from:"bgs", to:"twin-primes", shared:"zero distribution (fine structure of zero spectrum)"},
  {from:"bgs", to:"twin-primes", shared:"zero distribution (level repulsion input)"},
  {from:"bgs", to:"vp-vs-vnp", shared:"Galois representation (Kronecker asymptotics ↔ GUE statistics)"},
  {from:"bgs", to:"ym", shared:"ITPFI factor type (type III$_1$ via ergodic modular flow)"},
  {from:"bgs", to:"ym", shared:"ergodic property (gradient-flow contractivity)"},
  {from:"bgs", to:"ym", shared:"ergodic property (k-independent polymer convergence)"},
  {from:"bgs", to:"ym", shared:"gauge class / Brauer class"},
  {from:"bgs", to:"ym", shared:"scaling dimension (Pattern 5 zeta-regularization)"},
  {from:"bsd", to:"goldbach", shared:"BC-KMS state + ITPFI decomposition"},
  {from:"bsd", to:"goldbach", shared:"C*-algebra structure (BC over imaginary quadratic $K$)"},
  {from:"bsd", to:"goldbach", shared:"L-value (face-only ARITHMETIC)"},
  {from:"bsd", to:"goldbach", shared:"L-value local Euler factors (face-only ARITHMETIC)"},
  {from:"bsd", to:"grh", shared:"BC-KMS state"},
  {from:"bsd", to:"grh", shared:"C*-algebra structure + Hecke-character bound"},
  {from:"bsd", to:"grh", shared:"CCM 2025 dependency"},
  {from:"bsd", to:"grh", shared:"Galois representation / zero distribution"},
  {from:"bsd", to:"grh", shared:"spectral gap / limit structure"},
  {from:"bsd", to:"grh", shared:"zero distribution"},
  {from:"bsd", to:"grh", shared:"zero distribution (GRH for CM characters strengthens BSD)"},
  {from:"bsd", to:"h12", shared:"C*-algebra structure (Hecke eigenvalues)"},
  {from:"bsd", to:"h12", shared:"C*-algebra structure (cocycle machinery over Q)"},
  {from:"bsd", to:"h12", shared:"C*-algebra structure (local Brauer group integrality)"},
  {from:"bsd", to:"h12", shared:"Galois representation"},
  {from:"bsd", to:"h12", shared:"Galois representation (Hecke characters for CM curves)"},
  {from:"bsd", to:"h12", shared:"Galois representation (Hecke-character arithmetic)"},
  {from:"bsd", to:"h12", shared:"Galois representation (explicit CFT adjacency)"},
  {from:"bsd", to:"hilbert-6", shared:"C*-algebra structure"},
  {from:"bsd", to:"hodge", shared:"CM abelian-variety slice inherits arXiv:2510.21562; paper29 programme-graph-edge"},
  {from:"bsd", to:"hodge", shared:"CM motives on abelian varieties inherit from endomotive structure; paper29 progr"},
  {from:"bsd", to:"hodge", shared:"CM-abelian André motivated recovery — bypass direction"},
  {from:"bsd", to:"hodge", shared:"CM-abelian route composition analog"},
  {from:"bsd", to:"hodge", shared:"Galois representation"},
  {from:"bsd", to:"hodge", shared:"Galois representation / L-value"},
  {from:"bsd", to:"hodge", shared:"Hodge decomposition on CM abelian varieties ↔ Selmer-dual structure"},
  {from:"bsd", to:"hodge", shared:"L-value (Hodge adjacent)"},
  {from:"bsd", to:"katz-sarnak", shared:"C*-algebra structure (Hecke cocycle bound)"},
  {from:"bsd", to:"katz-sarnak", shared:"Galois representation"},
  {from:"bsd", to:"katz-sarnak", shared:"Galois representation ($SO^\\pm$ slice at elliptic curves)"},
  {from:"bsd", to:"katz-sarnak", shared:"face-only (symmetry-type statistics for ranks)"},
  {from:"bsd", to:"katz-sarnak", shared:"zero distribution"},
  {from:"bsd", to:"katz-sarnak", shared:"zero distribution ($SO^\\pm$ split via rank parity, PRIMARY K-S ↔ BSD EDGE)"},
  {from:"bsd", to:"katz-sarnak", shared:"zero distribution (ITPFI local-global structure)"},
  {from:"bsd", to:"katz-sarnak", shared:"zero distribution (quadratic twists of E-curves at Sp-analog)"},
  {from:"bsd", to:"lehmer", shared:"Galois representation (CM abelian-variety slice)"},
  {from:"bsd", to:"lehmer", shared:"L-value"},
  {from:"bsd", to:"lehmer", shared:"L-value (CM curves' L-value stability)"},
  {from:"bsd", to:"lehmer", shared:"face-only (cross-Clay outer-ring structure)"},
  {from:"bsd", to:"lehmer", shared:"spectral gap (CP² × S² $H^{1,1} = 1$ TOPOLOGY rigidity)"},
  {from:"bsd", to:"opn", shared:": - Reason: paper60 §25 EXPLICIT: the BSD template is OPN's structural parent"},
  {from:"bsd", to:"opn", shared:"ARITHMETIC outer-ring closure"},
  {from:"bsd", to:"opn", shared:"BC-KMS state + dark-state projector structure"},
  {from:"bsd", to:"opn", shared:"ITPFI factor type (bridge family / local Euler factors)"},
  {from:"bsd", to:"opn", shared:"ITPFI factor type (cocycle shift)"},
  {from:"bsd", to:"opn", shared:"ITPFI factor type + BC-KMS state"},
  {from:"bsd", to:"opn", shared:"L-value bound via GRH"},
  {from:"bsd", to:"opn", shared:"gauge class (number-field prime structure)"},
  {from:"bsd", to:"pvnp", shared:"BC-KMS state"},
  {from:"bsd", to:"pvnp", shared:"BC-KMS state (CM L-functions via BC structure)"},
  {from:"bsd", to:"pvnp", shared:"BC-KMS state (faithfulness)"},
  {from:"bsd", to:"pvnp", shared:"C\\*-algebra structure (Hecke groupoid)"},
  {from:"bsd", to:"pvnp", shared:"C\\*-algebra structure (Hecke-operator membership analog)"},
  {from:"bsd", to:"pvnp", shared:"Clay-grade closure"},
  {from:"bsd", to:"pvnp", shared:"ITPFI factor type"},
  {from:"bsd", to:"pvnp", shared:"P4 rigidity"},
  {from:"bsd", to:"qg5d", shared:"gauge class (Brauer β_3 at Gaussian primes), L-value (L(E, s))"},
  {from:"bsd", to:"rh", shared:"BC-KMS state"},
  {from:"bsd", to:"rh", shared:"BC-KMS state, C*-algebra structure"},
  {from:"bsd", to:"rh", shared:"C*-algebra structure"},
  {from:"bsd", to:"rh", shared:"Galois representation"},
  {from:"bsd", to:"rh", shared:"Galois representation / zero distribution"},
  {from:"bsd", to:"rh", shared:"ITPFI factor type"},
  {from:"bsd", to:"rh", shared:"L-value"},
  {from:"bsd", to:"rh", shared:"L-value (Clay-grade closure)"},
  {from:"bsd", to:"rh", shared:"L-value / holonomy"},
  {from:"bsd", to:"rh", shared:"critical exponent"},
  {from:"bsd", to:"rh", shared:"spectral gap (generalized)"},
  {from:"bsd", to:"rh", shared:"transcendence / zero distribution"},
  {from:"bsd", to:"rh", shared:"zero distribution"},
  {from:"bsd", to:"sato-tate", shared:"BC-KMS state (BC algebra over $K$)"},
  {from:"bsd", to:"sato-tate", shared:"BC-KMS state / ITPFI factor type"},
  {from:"bsd", to:"sato-tate", shared:"Galois representation (Hecke L)"},
  {from:"bsd", to:"sato-tate", shared:"Galois representation (bridge family cocycles)"},
  {from:"bsd", to:"sato-tate", shared:"ITPFI factor type (CM AVs dim ≥ 2)"},
  {from:"bsd", to:"sato-tate", shared:"ITPFI factor type (type III$_{1/N(\\mathfrak{p})}$)"},
  {from:"bsd", to:"sato-tate", shared:"zero distribution"},
  {from:"bsd", to:"schanuel", shared:"BC-KMS state"},
  {from:"bsd", to:"schanuel", shared:"L-value (sibling algebraic independence)"},
  {from:"bsd", to:"schanuel", shared:"L-value (transcendence)"},
  {from:"bsd", to:"schanuel", shared:"L-value pin content"},
  {from:"bsd", to:"schanuel", shared:"transcendence content"},
  {from:"bsd", to:"twin-primes", shared:"L-value (face-only ARITHMETIC)"},
  {from:"bsd", to:"ym", shared:"BC-KMS state"},
  {from:"bsd", to:"ym", shared:"C*-algebra structure"},
  {from:"bsd", to:"ym", shared:"Clay-grade closure (same $P_O$ status)"},
  {from:"bsd", to:"ym", shared:"critical exponent / P4 rigidity"},
  {from:"bsd", to:"ym", shared:"gauge class / Galois representation (cross-face)"},
  {from:"collatz", to:"cramer", shared:"ITPFI factor type"},
  {from:"collatz", to:"cramer", shared:"ITPFI factor type (Hecke operator commutation)"},
  {from:"collatz", to:"cramer", shared:"ITPFI factor type (tensor decomposition $\\omega_1 = \\otimes_p \\omega_1^{(p)}$)"},
  {from:"collatz", to:"cramer", shared:"ergodic property (Kac's-lemma return-time envelope analog)"},
  {from:"collatz", to:"cramer", shared:"ergodic property (modular-flow canonical)"},
  {from:"collatz", to:"cramer", shared:"face-adjacency (HARMONICS ↔ DYNAMICS siblings) and shared invariant (ergodic property / Hecke commutation)"},
  {from:"collatz", to:"cramer", shared:"face-only (three-face-triangle outer-ring closure pattern)"},
  {from:"collatz", to:"goldbach", shared:"HARMONICS face + Mellin-dual framing"},
  {from:"collatz", to:"goldbach", shared:"additive-multiplicative wall"},
  {from:"collatz", to:"goldbach", shared:"additive-vs-multiplicative interface"},
  {from:"collatz", to:"grh", shared:"HARMONICS face"},
  {from:"collatz", to:"h12", shared:"C*-algebra structure (Hecke operators on BC)"},
  {from:"collatz", to:"h12", shared:"face-only (Mori 2024 Cuntz $\\mathcal{O}_2$ formulation parallel)"},
  {from:"collatz", to:"lehmer", shared:"BC-KMS state (phase-transition mechanism)"},
  {from:"collatz", to:"lehmer", shared:"ITPFI factor type"},
  {from:"collatz", to:"lehmer", shared:"face-only (HARMONICS sibling ground state)"},
  {from:"collatz", to:"lehmer", shared:"face-only (three-face triangle outer-ring)"},
  {from:"collatz", to:"lehmer", shared:"face-only (three-face-triangle outer-ring closure pattern)"},
  {from:"collatz", to:"lehmer", shared:"face-sibling (HARMONICS ↔ TOPOLOGY siblings)"},
  {from:"collatz", to:"lindelof", shared:"spectral gap (HARMONICS canonical)"},
  {from:"collatz", to:"opn", shared:"BC-KMS state"},
  {from:"collatz", to:"opn", shared:"ITPFI factor type ($(2,3)$-adic sub-tensor)"},
  {from:"collatz", to:"opn", shared:"additive-multiplicative wall"},
  {from:"collatz", to:"opn", shared:"additive-vs-multiplicative interface"},
  {from:"collatz", to:"pvnp", shared:"C*-algebra structure"},
  {from:"collatz", to:"pvnp", shared:"ITPFI factor type (type III$_1$ rigidity)"},
  {from:"collatz", to:"pvnp", shared:"ergodic property"},
  {from:"collatz", to:"pvnp", shared:"spectral gap"},
  {from:"collatz", to:"qg5d", shared:"ergodic property, holonomy"},
  {from:"collatz", to:"rh", shared:"spectral gap (uniform-constant framework)"},
  {from:"collatz", to:"sato-tate", shared:"BC-KMS state (spectral harmonics)"},
  {from:"collatz", to:"sato-tate", shared:"ergodic property (entropy / equidistribution)"},
  {from:"collatz", to:"twin-primes", shared:"Hecke-semigroup framework"},
  {from:"collatz", to:"twin-primes", shared:"face-only (HARMONICS-face shared additive-multiplicative interface)"},
  {from:"collatz", to:"twin-primes", shared:"face-only (additive-multiplicative interface)"},
  {from:"collatz", to:"twin-primes", shared:"face-only (sieve parity)"},
  {from:"collatz", to:"ym", shared:"C*-algebra structure (operator-valued-distribution analog)"},
  {from:"collatz", to:"ym", shared:"KK mode index (HARMONICS alternative)"},
  {from:"collatz", to:"ym", shared:"KK mode index (integer-harmonic framework)"},
  {from:"collatz", to:"ym", shared:"ergodic property"},
  {from:"collatz", to:"ym", shared:"projection-shared ($P_O$ outer-ring closure)"},
  {from:"collatz", to:"ym", shared:"spectral gap"},
  {from:"cramer", to:"goldbach", shared:"ITPFI factor type (Mertens in circle method)"},
  {from:"cramer", to:"goldbach", shared:"L-value (explicit formula input)"},
  {from:"cramer", to:"goldbach", shared:"ergodic property (bulk counterpart)"},
  {from:"cramer", to:"goldbach", shared:"ergodic property (bulk of same distribution)"},
  {from:"cramer", to:"grh", shared:"DYNAMICS face"},
  {from:"cramer", to:"h12", shared:"ITPFI factor type (Mertens as class-field temperature)"},
  {from:"cramer", to:"h12", shared:"L-value"},
  {from:"cramer", to:"h12", shared:"face-only (Mertens constant $e^{-\\gamma}$ H12-Cramér chord)"},
  {from:"cramer", to:"hilbert-6", shared:"ergodic property (DYNAMICS canonical face-match)"},
  {from:"cramer", to:"katz-sarnak", shared:"ergodic property (symmetry-type unitary ensemble)"},
  {from:"cramer", to:"katz-sarnak", shared:"zero distribution (extreme-value differentiation)"},
  {from:"cramer", to:"katz-sarnak", shared:"zero distribution (symmetry-type universality)"},
  {from:"cramer", to:"lehmer", shared:"BC-KMS state (modular flow at $\\beta = 1$)"},
  {from:"cramer", to:"lehmer", shared:"BC-KMS state (sibling two-face dual)"},
  {from:"cramer", to:"lehmer", shared:"BC-KMS state (sibling two-face picture)"},
  {from:"cramer", to:"lehmer", shared:"ITPFI factor type (SIBLING, S-DUAL-CONSTRUCT-BRIDGED)"},
  {from:"cramer", to:"lehmer", shared:"face-only + shared ergodic property (SIBLING outer-ring closure)"},
  {from:"cramer", to:"lehmer", shared:"face-only + shared spectral gap (SIBLING outer-ring closure)"},
  {from:"cramer", to:"lehmer", shared:"spectral gap + ITPFI factor type"},
  {from:"cramer", to:"lindelof", shared:"L-value"},
  {from:"cramer", to:"lindelof", shared:"L-value (amplitude-bound framework)"},
  {from:"cramer", to:"lindelof", shared:"OUTGOING PRIMARY: Lindelöf → Cramér shortcut"},
  {from:"cramer", to:"ns", shared:"ergodic property"},
  {from:"cramer", to:"ns", shared:"ergodic property (DYNAMICS canonical)"},
  {from:"cramer", to:"pvnp", shared:"ITPFI factor type (III$_1$)"},
  {from:"cramer", to:"pvnp", shared:"ITPFI factor type (Popa-rigidity analog on same structure)"},
  {from:"cramer", to:"pvnp", shared:"ergodic property (DYNAMICS canonical)"},
  {from:"cramer", to:"pvnp", shared:"ergodic property (DYNAMICS canonical, essentially-free flow)"},
  {from:"cramer", to:"pvnp", shared:"ergodic property (Popa rigidity analog)"},
  {from:"cramer", to:"pvnp", shared:"ergodic property (strong ergodicity)"},
  {from:"cramer", to:"pvnp", shared:"ergodic property (type III$_1$ rigidity)"},
  {from:"cramer", to:"qg5d", shared:"BC-KMS state + modular flow"},
  {from:"cramer", to:"qg5d", shared:"ITPFI factor type"},
  {from:"cramer", to:"qg5d", shared:"ergodic property, zero distribution"},
  {from:"cramer", to:"rh", shared:"BC-KMS state (CCM gate, L3 Check 3 is conditional)"},
  {from:"cramer", to:"rh", shared:"ITPFI factor type (Euler product regularization)"},
  {from:"cramer", to:"rh", shared:"L-value (explicit formula)"},
  {from:"cramer", to:"rh", shared:"L-value (same error-term control)"},
  {from:"cramer", to:"rh", shared:"ergodic property"},
  {from:"cramer", to:"rh", shared:"face-only (outer-ring famous conjecture)"},
  {from:"cramer", to:"rh", shared:"spectral gap (DYNAMICS)"},
  {from:"cramer", to:"sato-tate", shared:"ergodic property (Haar pushforward analog)"},
  {from:"cramer", to:"sato-tate", shared:"ergodic property (modular-flow ergodicity)"},
  {from:"cramer", to:"sato-tate", shared:"zero distribution (Haar extreme-value analog)"},
  {from:"cramer", to:"turbulence", shared:"ergodic property"},
  {from:"cramer", to:"turbulence", shared:"ergodic property (DYNAMICS canonical)"},
  {from:"cramer", to:"twin-primes", shared:"ITPFI factor type (Hardy-Littlewood $C_2$ constant parallel)"},
  {from:"cramer", to:"twin-primes", shared:"L-value (explicit formula input)"},
  {from:"cramer", to:"twin-primes", shared:"L-value (singular-series at opposite tail)"},
  {from:"cramer", to:"twin-primes", shared:"ergodic property (small-$s$ tail of same sine kernel)"},
  {from:"cramer", to:"twin-primes", shared:"ergodic property (small-gap counterpart)"},
  {from:"cramer", to:"twin-primes", shared:"zero distribution (prime-gap statistics)"},
  {from:"cramer", to:"twin-primes", shared:"zero distribution (same universality-class issue on other tail)"},
  {from:"cramer", to:"twin-primes", shared:"zero distribution (three-tail structure)"},
  {from:"cramer", to:"twin-primes", shared:"zero distribution via prime-gap dynamics"},
  {from:"cramer", to:"ym", shared:"ITPFI factor type (contraction-mapping RG analog)"},
  {from:"cramer", to:"ym", shared:"L-value (convergent amplitude sum analog)"},
  {from:"cramer", to:"ym", shared:"ergodic property"},
  {from:"cramer", to:"ym", shared:"ergodic property (RG-step uniformity analog)"},
  {from:"cramer", to:"ym", shared:"face-only (DYNAMICS canonical)"},
  {from:"cramer", to:"ym", shared:"scaling dimension (modular-flow contraction)"},
  {from:"goldbach", to:"grh", shared:"zero distribution (prime density in progressions)"},
  {from:"goldbach", to:"katz-sarnak", shared:"zero distribution (density-per-family type)"},
  {from:"goldbach", to:"lindelof", shared:"outgoing (via Cramér)"},
  {from:"goldbach", to:"opn", shared:"$\\mu_p$ generation / ARITHMETIC face"},
  {from:"goldbach", to:"opn", shared:"$\\mu_p$ generators / BC entry"},
  {from:"goldbach", to:"opn", shared:"ITPFI / multiplicative structure"},
  {from:"goldbach", to:"opn", shared:"additive-multiplicative wall structure"},
  {from:"goldbach", to:"opn", shared:"multiplicative structure"},
  {from:"goldbach", to:"opn", shared:"zero distribution (explicit formula)"},
  {from:"goldbach", to:"pvnp", shared:"BC-KMS state + C*-algebra structure"},
  {from:"goldbach", to:"pvnp", shared:"scaling dimension"},
  {from:"goldbach", to:"pvnp", shared:"scaling dimension (integer count)"},
  {from:"goldbach", to:"qg5d", shared:"C*-algebra structure"},
  {from:"goldbach", to:"qg5d", shared:"C*-algebra structure + BC-KMS state"},
  {from:"goldbach", to:"qg5d", shared:"C*-algebra structure, holonomy"},
  {from:"goldbach", to:"rh", shared:"ARITHMETIC (Euler product)"},
  {from:"goldbach", to:"rh", shared:"BC-KMS state"},
  {from:"goldbach", to:"rh", shared:"C*-algebra structure (BC-algebra ITPFI factorization)"},
  {from:"goldbach", to:"rh", shared:"ITPFI factor type + Euler product"},
  {from:"goldbach", to:"rh", shared:"critical exponent (ARITHMETIC canonical)"},
  {from:"goldbach", to:"rh", shared:"explicit formula + spectral gap"},
  {from:"goldbach", to:"rh", shared:"zero distribution"},
  {from:"goldbach", to:"rh", shared:"zero distribution (circle method consumes RH)"},
  {from:"goldbach", to:"sato-tate", shared:"face-only (MEASURE canonical)"},
  {from:"goldbach", to:"schanuel", shared:"face-only (ARITHMETIC South trough)"},
  {from:"goldbach", to:"twin-primes", shared:"**PRIMARY EDGE (shared wall)**"},
  {from:"goldbach", to:"twin-primes", shared:"**PRIMARY EDGE**"},
  {from:"goldbach", to:"twin-primes", shared:"ARITHMETIC + $\\mu_p$ generation"},
  {from:"goldbach", to:"twin-primes", shared:"additive-multiplicative wall + ARITHMETIC"},
  {from:"goldbach", to:"twin-primes", shared:"explicit formula (prime gaps ↔ zero spacing)"},
  {from:"goldbach", to:"twin-primes", shared:"multiplicative structure"},
  {from:"goldbach", to:"twin-primes", shared:"novel arithmetic-correction structure"},
  {from:"goldbach", to:"twin-primes", shared:"zero distribution (GUE bulk)"},
  {from:"goldbach", to:"twin-primes", shared:"zero distribution (Mellin bridge)"},
  {from:"goldbach", to:"twin-primes", shared:"zero distribution (pair correlation)"},
  {from:"goldbach", to:"twin-primes", shared:"zero distribution (sieve methods)"},
  {from:"goldbach", to:"vp-vs-vnp", shared:"scaling dimension (ARITHMETIC canonical)"},
  {from:"goldbach", to:"ym", shared:"KK mode index (integer-power-sum on circle)"},
  {from:"goldbach", to:"ym", shared:"KK mode index / integer-lattice (speculative)"},
  {from:"grh", to:"h12", shared:"C*-algebra structure (via character twist)"},
  {from:"grh", to:"h12", shared:"Galois representation"},
  {from:"grh", to:"h12", shared:"Galois representation (Dirichlet characters = bridge-character subfamily)"},
  {from:"grh", to:"h12", shared:"Galois representation (cyclotomic tower closure)"},
  {from:"grh", to:"h12", shared:"Galois representation (cyclotomic tower)"},
  {from:"grh", to:"katz-sarnak", shared:"C*-algebra structure (BC$_\\chi$ construction)"},
  {from:"grh", to:"katz-sarnak", shared:"Galois representation ($\\{U, Sp\\}$ slice at Dirichlet)"},
  {from:"grh", to:"katz-sarnak", shared:"Galois representation (Dirichlet-character K-S inheritance)"},
  {from:"grh", to:"katz-sarnak", shared:"Galois representation + zero distribution"},
  {from:"grh", to:"katz-sarnak", shared:"Galois representation / bridge family selector"},
  {from:"grh", to:"katz-sarnak", shared:"ITPFI factor type (Dirichlet-quadratic at bridge $k=2$)"},
  {from:"grh", to:"lindelof", shared:"L-value ($\\chi$-twisted analog)"},
  {from:"grh", to:"lindelof", shared:"scaling dimension (uniform amplitude control)"},
  {from:"grh", to:"lindelof", shared:"zero distribution (GRH → Lindelöf)"},
  {from:"grh", to:"lindelof", shared:"zero-distribution (GRH → Lindelöf for all $L(s,\\chi)$)"},
  {from:"grh", to:"pvnp", shared:"BC-KMS state"},
  {from:"grh", to:"pvnp", shared:"zero distribution (progression error $O(\\sqrt{x}\\log^2 x)$ feeds spectral-gap lower bound)"},
  {from:"grh", to:"qg5d", shared:"L-value (Dirichlet L(s, χ)), BC-KMS state (BC_χ twist), Galois representation"},
  {from:"grh", to:"rh", shared:"BC-KMS state (uniqueness)"},
  {from:"grh", to:"rh", shared:"C*-algebra structure + spectral gap"},
  {from:"grh", to:"rh", shared:"CCM 2025 dependency + spectral gap"},
  {from:"grh", to:"rh", shared:"ITPFI factor type"},
  {from:"grh", to:"rh", shared:"L-value"},
  {from:"grh", to:"rh", shared:"critical exponent"},
  {from:"grh", to:"rh", shared:"scaling dimension (all four estimates)"},
  {from:"grh", to:"rh", shared:"spectral gap"},
  {from:"grh", to:"rh", shared:"spectral gap (Boegli untwisted → χ-twisted)"},
  {from:"grh", to:"rh", shared:"strict dependency + shared C*-algebra structure"},
  {from:"grh", to:"rh", shared:"zero distribution (Hurwitz untwisted → χ-twisted)"},
  {from:"grh", to:"rh", shared:"zero distribution (χ-generalization of conclusion)"},
  {from:"grh", to:"sato-tate", shared:"L-value structure (symmetric-power L-functions)"},
  {from:"grh", to:"sato-tate", shared:"MEASURE face (equidistribution via product measure)"},
  {from:"grh", to:"sato-tate", shared:"zero distribution (Chebyshev-bias consequences)"},
  {from:"grh", to:"sato-tate", shared:"zero distribution (GRH as special case)"},
  {from:"grh", to:"sato-tate", shared:"zero distribution (Hecke L-function GRH)"},
  {from:"grh", to:"sato-tate", shared:"zero distribution (automorphic Langlands)"},
  {from:"grh", to:"sato-tate", shared:"zero distribution (equidistribution of Frobenius for Dirichlet)"},
  {from:"grh", to:"twin-primes", shared:"L-value (GRH + EH improvements)"},
  {from:"grh", to:"twin-primes", shared:"L-value (GRH-conditional closure of L3 → L5)"},
  {from:"grh", to:"twin-primes", shared:"zero distribution (Elliott-Halberstam)"},
  {from:"grh", to:"twin-primes", shared:"zero distribution (GRH + Elliott-Halberstam → gaps ≤ 6)"},
  {from:"grh", to:"ym", shared:"BC-KMS state"},
  {from:"grh", to:"ym", shared:"RESONANCE face (spectral exactness ↔ OS reconstruction limit)"},
  {from:"grh", to:"ym", shared:"scaling dimension (k-independent uniform bound)"},
  {from:"grh", to:"ym", shared:"spectral gap (k-independent constant)"},
  {from:"h12", to:"hodge", shared:"Galois representation (motivic Galois action)"},
  {from:"h12", to:"hodge", shared:"Galois representation (motivic Galois on cyclotomic motives)"},
  {from:"h12", to:"hodge", shared:"class fields → motives via BC algebra; paper29 programme-graph-edge"},
  {from:"h12", to:"hodge", shared:"class-field + motivic composition analog"},
  {from:"h12", to:"hodge", shared:"motivic Galois acts on Hodge structure ↔ class-field Galois acts on L-values"},
  {from:"h12", to:"hodge", shared:"motivic Galois ↔ class field Galois parallel"},
  {from:"h12", to:"hodge", shared:"motivic hom/num equivalence ↔ class-field equivalence parallel"},
  {from:"h12", to:"hodge", shared:"motivic-class-field correspondence analog"},
  {from:"h12", to:"katz-sarnak", shared:"Galois representation"},
  {from:"h12", to:"katz-sarnak", shared:"Galois representation (BC representation type = symmetry type)"},
  {from:"h12", to:"katz-sarnak", shared:"Galois representation (bridge family = symmetry-type selector)"},
  {from:"h12", to:"katz-sarnak", shared:"Galois representation (classification of Galois-repn over $\\mathbb{Q}$)"},
  {from:"h12", to:"katz-sarnak", shared:"Galois representation (every L-function family has a symmetry type)"},
  {from:"h12", to:"lehmer", shared:"BC-KMS state (Hilbert 12 IS $\\beta > 1$ regime)"},
  {from:"h12", to:"lehmer", shared:"KK mode index (Kronecker units on e-circle)"},
  {from:"h12", to:"lehmer", shared:"L-value (class-field regulator)"},
  {from:"h12", to:"lehmer", shared:"face-only (complementary outer-ring — boundary vs interior)"},
  {from:"h12", to:"pvnp", shared:"C*-algebra structure (type III$_1$ factor inheritance)"},
  {from:"h12", to:"pvnp", shared:"Galois representation (Popa rigidity ↔ Brauer-class rigidity)"},
  {from:"h12", to:"qg5d", shared:"C*-algebra structure (BC algebra foundation)"},
  {from:"h12", to:"qg5d", shared:"Galois representation (general-K open"},
  {from:"h12", to:"qg5d", shared:"Galois representation), gauge class (Brauer β_k), monodromy"},
  {from:"h12", to:"rh", shared:"BC-KMS state (Brauer-KMS duality → RH corollary)"},
  {from:"h12", to:"rh", shared:"BC-KMS state (different $\\beta$)"},
  {from:"h12", to:"rh", shared:"C*-algebra structure"},
  {from:"h12", to:"rh", shared:"Galois representation (Stark-phase failure does NOT affect RH path via CCM)"},
  {from:"h12", to:"sato-tate", shared:"BC-KMS state"},
  {from:"h12", to:"sato-tate", shared:"Galois representation (Hecke Grössencharakter)"},
  {from:"h12", to:"sato-tate", shared:"Galois representation (explicit class-field construction)"},
  {from:"h12", to:"vp-vs-vnp", shared:"C*-algebra structure (class-field-theoretic continuous analog)"},
  {from:"h12", to:"ym", shared:"C*-algebra structure (local C*-algebra via Brauer cocycle)"},
  {from:"h12", to:"ym", shared:"Galois representation (group complexification)"},
  {from:"h12", to:"ym", shared:"gauge class (Galois complexification)"},
  {from:"hilbert-6", to:"katz-sarnak", shared:"gauge class (SYMMETRY canonical)"},
  {from:"hilbert-6", to:"ns", shared:"C*-algebra structure"},
  {from:"hilbert-6", to:"ns", shared:"ergodic property (DYNAMICS)"},
  {from:"hilbert-6", to:"pvnp", shared:"BC-KMS state + type III_1"},
  {from:"hilbert-6", to:"qg5d", shared:"BC-KMS state"},
  {from:"hilbert-6", to:"qg5d", shared:"BC-KMS state (36/36 match)"},
  {from:"hilbert-6", to:"qg5d", shared:"BC-KMS state (matrix elements)"},
  {from:"hilbert-6", to:"qg5d", shared:"C*-algebra structure (THE META-CLOSURE)"},
  {from:"hilbert-6", to:"qg5d", shared:"C*-algebra structure (universal closure)"},
  {from:"hilbert-6", to:"qg5d", shared:"CURVATURE (GR recovery)"},
  {from:"hilbert-6", to:"qg5d", shared:"every invariant (this is the \"axiomatization of physics\" closure)"},
  {from:"hilbert-6", to:"qg5d", shared:"gauge class"},
  {from:"hilbert-6", to:"rh", shared:"BC-KMS state"},
  {from:"hilbert-6", to:"rh", shared:"scaling dimension (γ log-spectrum)"},
  {from:"hilbert-6", to:"sato-tate", shared:"ergodic property (MEASURE canonical)"},
  {from:"hilbert-6", to:"schanuel", shared:"L-value / scaling dimension"},
  {from:"hilbert-6", to:"turbulence", shared:"C*-algebra structure (fluid/gravity duality)"},
  {from:"hilbert-6", to:"turbulence", shared:"ergodic property (downstream of fluid limit)"},
  {from:"hilbert-6", to:"ym", shared:"BC-KMS state (Wightman/OS recovery)"},
  {from:"hilbert-6", to:"ym", shared:"gauge class (SYMMETRY face)"},
  {from:"hodge", to:"katz-sarnak", shared:"SYMMETRY canonical, group-from-category; paper60 §12 Tannakian parallel"},
  {from:"hodge", to:"katz-sarnak", shared:"monodromy (monodromy as symmetry-type selector)"},
  {from:"hodge", to:"katz-sarnak", shared:"symmetry-type classification of Langlands duals"},
  {from:"hodge", to:"lehmer", shared:"Galois representation"},
  {from:"hodge", to:"lehmer", shared:"L-value (motivic bridge via Standard Conjecture D)"},
  {from:"hodge", to:"lehmer", shared:"L-value (motivic cohomology bridge)"},
  {from:"hodge", to:"lehmer", shared:"TOPOLOGY canonical — integer-class rigidity / cyclotomic-protection structural p"},
  {from:"hodge", to:"lehmer", shared:"face-only (cross-Clay outer-ring structure)"},
  {from:"hodge", to:"qg5d", shared:"(unspecified)"},
  {from:"hodge", to:"qg5d", shared:"gauge class (Hodge class (p,p)), scaling dimension (Hodge decomposition strata)"},
  {from:"hodge", to:"rh", shared:"Hodge-compatibility ↔ CCM spectral-realization compatibility analog"},
  {from:"hodge", to:"rh", shared:"Langlands dual ↔ functional-equation duality — SPECULATIVE"},
  {from:"hodge", to:"rh", shared:"two-route structure: CCM spectral + functional-equation ↔ two-route Hodge"},
  {from:"hodge", to:"rh", shared:"zeros ↔ endomotive spectral data; paper29 programme-graph-edge \"RH zeros → endom"},
  {from:"hodge", to:"sato-tate", shared:"Galois representation (motivic Galois group)"},
  {from:"hodge", to:"sato-tate", shared:"Galois representation (motivic-conjecture closure)"},
  {from:"hodge", to:"sato-tate", shared:"Galois representation / monodromy (Langlands)"},
  {from:"hodge", to:"schanuel", shared:"Galois representation"},
  {from:"hodge", to:"schanuel", shared:"Galois representation (sibling transcendence)"},
  {from:"hodge", to:"schanuel", shared:"Galois representation / transcendental realization"},
  {from:"hodge", to:"schanuel", shared:"L-value (periods as pins)"},
  {from:"hodge", to:"schanuel", shared:"monodromy (motivic Schanuel)"},
  {from:"hodge", to:"schanuel", shared:"period relations constrained by $G_{\\text{mot}}$-invariance — paper29 programme-"},
  {from:"hodge", to:"schanuel", shared:"period-relation functoriality — paper29 programme-graph-edge"},
  {from:"hodge", to:"turbulence", shared:"scaling dimension"},
  {from:"hodge", to:"twin-primes", shared:"L-value (motivic period framing)"},
  {from:"hodge", to:"vp-vs-vnp", shared:": recorded"},
  {from:"hodge", to:"vp-vs-vnp", shared:"C*-algebra structure + Galois representation (P_B / P1)"},
  {from:"hodge", to:"vp-vs-vnp", shared:"Galois representation (Tannakian ↔ GCT representation-theoretic classification)"},
  {from:"hodge", to:"vp-vs-vnp", shared:"Galois representation + C*-algebra structure (two-route composition)"},
  {from:"hodge", to:"vp-vs-vnp", shared:"scaling dimension (P4 closure-rigidity pattern)"},
  {from:"hodge", to:"vp-vs-vnp", shared:"scaling dimension (motivic functoriality ↔ p-projection functoriality)"},
  {from:"hodge", to:"ym", shared:"CP^{N-1} internal space vs CP² × S² — Kähler structural family; paper60 §13 SYMM"},
  {from:"hodge", to:"ym", shared:"RESONANCE canonical — Schwinger functions / operator-valued distributions are th"},
  {from:"hodge", to:"ym", shared:"dim-6 operator classification by symmetry type ↔ Std Conj D scaling-dimension se"},
  {from:"hodge", to:"ym", shared:"gauge class (C symmetry)"},
  {from:"hodge", to:"ym", shared:"group complexification SL(N,ℂ"},
  {from:"hodge", to:"ym", shared:"route-split: $P_O$-vs-$P_B$ branching decision — same structural shape of \"which"},
  {from:"hodge", to:"ym", shared:"scaling dimension (dim-6 stratum)"},
  {from:"katz-sarnak", to:"lehmer", shared:"Galois representation (symmetry-type at automorphism level)"},
  {from:"katz-sarnak", to:"lindelof", shared:"L-value (moment-amplitude connection)"},
  {from:"katz-sarnak", to:"lindelof", shared:"L-value (moment-density connection)"},
  {from:"katz-sarnak", to:"lindelof", shared:"scaling dimension (double-sum-of-primes boundary)"},
  {from:"katz-sarnak", to:"ns", shared:"face-only (SYMMETRY canonical)"},
  {from:"katz-sarnak", to:"opn", shared:"ITPFI factor type (local-global structure)"},
  {from:"katz-sarnak", to:"opn", shared:"ITPFI factor type (local-global)"},
  {from:"katz-sarnak", to:"opn", shared:"gauge class ($k=4$ bridge family)"},
  {from:"katz-sarnak", to:"pvnp", shared:"ITPFI factor type (Popa rigidity at III$_1$ = $U$-type)"},
  {from:"katz-sarnak", to:"pvnp", shared:"ergodic property (Haar measure)"},
  {from:"katz-sarnak", to:"pvnp", shared:"gauge class (Taylor classification $\\leftrightarrow$ symmetry-type classification)"},
  {from:"katz-sarnak", to:"pvnp", shared:"gauge class (non-amenable symmetry type)"},
  {from:"katz-sarnak", to:"pvnp", shared:"gauge class (symmetry-type classification of clones)"},
  {from:"katz-sarnak", to:"qg5d", shared:"Galois representation"},
  {from:"katz-sarnak", to:"qg5d", shared:"Galois representation (Pati-Salam orbifold)"},
  {from:"katz-sarnak", to:"qg5d", shared:"Galois representation (compound $P_D \\cap P_C$ closure per paper61 Vertex 25)"},
  {from:"katz-sarnak", to:"qg5d", shared:"ITPFI factor type"},
  {from:"katz-sarnak", to:"qg5d", shared:"ITPFI factor type (sub-route 5c IS the programme-specific test)"},
  {from:"katz-sarnak", to:"qg5d", shared:"gauge class, Galois representation"},
  {from:"katz-sarnak", to:"rh", shared:"C*-algebra structure (RH's BC algebra)"},
  {from:"katz-sarnak", to:"rh", shared:"Galois representation ($U$-type slice of K-S)"},
  {from:"katz-sarnak", to:"rh", shared:"Galois representation ($\\zeta$ at $U$-type)"},
  {from:"katz-sarnak", to:"rh", shared:"L-value (the ζ-moment problem)"},
  {from:"katz-sarnak", to:"rh", shared:"face-only (SYMMETRY canonical)"},
  {from:"katz-sarnak", to:"rh", shared:"monodromy (RH in function-field case via Weil)"},
  {from:"katz-sarnak", to:"rh", shared:"spectral gap (SYMMETRY canonical)"},
  {from:"katz-sarnak", to:"rh", shared:"zero distribution ($U$-type $n$-level correlations)"},
  {from:"katz-sarnak", to:"rh", shared:"zero distribution (Montgomery-Odlyzko at $U$)"},
  {from:"katz-sarnak", to:"rh", shared:"zero distribution (cuspidal L-function analog)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"Galois representation (Sato-Tate group selector)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"Galois representation (symmetry type = Sato-Tate group)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"Galois representation / monodromy"},
  {from:"katz-sarnak", to:"sato-tate", shared:"monodromy (CM case = $U(1)$ Sato-Tate group)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"monodromy (Haar equidistribution on conjugacy classes)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"monodromy (Langlands functoriality classifies symmetry types)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"zero distribution (Hecke Frobenius angles at O-type)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"zero distribution (elliptic Frobenius at $SO^\\pm$)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"zero distribution (elliptic-curve symmetry type O / SO$^\\pm$)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"zero distribution (generalized equidistribution)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"zero distribution (one-level equidistribution)"},
  {from:"katz-sarnak", to:"sato-tate", shared:"zero distribution / Galois representation"},
  {from:"katz-sarnak", to:"schanuel", shared:"face-only (Galois representation analog)"},
  {from:"katz-sarnak", to:"twin-primes", shared:"zero distribution (symmetry-type differentiates small-gap statistics)"},
  {from:"katz-sarnak", to:"twin-primes", shared:"zero distribution (unitary ensemble)"},
  {from:"katz-sarnak", to:"vp-vs-vnp", shared:"Galois representation (SYMMETRY canonical representation-type dictionary)"},
  {from:"katz-sarnak", to:"vp-vs-vnp", shared:"Galois representation (SYMMETRY canonical)"},
  {from:"katz-sarnak", to:"vp-vs-vnp", shared:"Galois representation (asymptotic representation-type classification)"},
  {from:"katz-sarnak", to:"ym", shared:"gauge class (bridge family $k=4$)"},
  {from:"katz-sarnak", to:"ym", shared:"scaling dimension (operator-family classification)"},
  {from:"lehmer", to:"lindelof", shared:"face-only (paper60 §13 adjacency table, Lehmer ↔ AMPLITUDE structural form of \"gap above ground state\")"},
  {from:"lehmer", to:"ns", shared:"face-only (gap-above-ground-state)"},
  {from:"lehmer", to:"opn", shared:"ARITHMETIC-lattice-rigidity (structural parallel)"},
  {from:"lehmer", to:"opn", shared:"face-only (programme-graph edge)"},
  {from:"lehmer", to:"opn", shared:"gauge class (cyclotomic arithmetic lattice)"},
  {from:"lehmer", to:"pvnp", shared:"ITPFI factor type (type III$_1$ at $\\beta = 1$)"},
  {from:"lehmer", to:"pvnp", shared:"spectral gap (Popa-rigidity analog)"},
  {from:"lehmer", to:"qg5d", shared:"BC-KMS state"},
  {from:"lehmer", to:"qg5d", shared:"BC-KMS state (phase transition at $\\beta = 1$)"},
  {from:"lehmer", to:"qg5d", shared:"holonomy = ℤ winding; cyclotomic roots of unity), gauge class (Brauer)"},
  {from:"lehmer", to:"qg5d", shared:"spectral gap (KK spectral gap analog)"},
  {from:"lehmer", to:"qg5d", shared:"spectral gap (empirical forcing)"},
  {from:"lehmer", to:"qg5d", shared:"spectral gap (primary parent"},
  {from:"lehmer", to:"rh", shared:"BC-KMS state (CCM spectral realization at critical line)"},
  {from:"lehmer", to:"rh", shared:"L-value (L-function analytic structure)"},
  {from:"lehmer", to:"rh", shared:"L-value (L-function non-vanishing at $s = 1$)"},
  {from:"lehmer", to:"rh", shared:"ergodic property (spectral-data pin-preservation)"},
  {from:"lehmer", to:"rh", shared:"face-only (TOPOLOGY canonical, gap-above-ground-state)"},
  {from:"lehmer", to:"sato-tate", shared:"face / holonomy (TOPOLOGY canonical)"},
  {from:"lehmer", to:"schanuel", shared:"L-value (period relations constrain L-values)"},
  {from:"lehmer", to:"schanuel", shared:"TOPOLOGY face (canonical sibling)"},
  {from:"lehmer", to:"schanuel", shared:"TOPOLOGY-face structural form"},
  {from:"lehmer", to:"schanuel", shared:"face-only (programme-graph edge CANDIDATE)"},
  {from:"lehmer", to:"turbulence", shared:"face-only (gap-above-ground-state)"},
  {from:"lehmer", to:"twin-primes", shared:"face-only (cyclotomic structure underlies functional equation)"},
  {from:"lehmer", to:"ym", shared:"Galois representation (complexification analog)"},
  {from:"lehmer", to:"ym", shared:"face-only (gap-above-ground-state structural form)"},
  {from:"lehmer", to:"ym", shared:"face-only (gap-above-ground-state)"},
  {from:"lehmer", to:"ym", shared:"spectral gap (Weitzenböck structural parallel — PRIMARY STRUCTURAL EDGE)"},
  {from:"lehmer", to:"ym", shared:"spectral gap (mass-gap analog)"},
  {from:"lindelof", to:"ns", shared:"scaling dimension (AMPLITUDE canonical)"},
  {from:"lindelof", to:"opn", shared:"AMPLITUDE face (growth-rate bound)"},
  {from:"lindelof", to:"pvnp", shared:"BC-KMS state"},
  {from:"lindelof", to:"qg5d", shared:"BC-KMS state"},
  {from:"lindelof", to:"qg5d", shared:"L-value"},
  {from:"lindelof", to:"qg5d", shared:"outer-ring conjecture closure"},
  {from:"lindelof", to:"qg5d", shared:"scaling dimension (Epstein-zeta regulator)"},
  {from:"lindelof", to:"qg5d", shared:"scaling dimension, spectral gap (uniform resolvent bound)"},
  {from:"lindelof", to:"rh", shared:"BC-KMS state, ITPFI factor type III$_1$"},
  {from:"lindelof", to:"rh", shared:"ITPFI factor type III$_1$, BC-KMS state"},
  {from:"lindelof", to:"rh", shared:"L-value, scaling dimension (classical RH implies Lindelöf parent)"},
  {from:"lindelof", to:"rh", shared:"parent edge (inherit-from)"},
  {from:"lindelof", to:"rh", shared:"scaling dimension"},
  {from:"lindelof", to:"rh", shared:"scaling dimension (AMPLITUDE canonical)"},
  {from:"lindelof", to:"rh", shared:"scaling dimension, L-value"},
  {from:"lindelof", to:"sato-tate", shared:"scaling dimension (sym$^k$ L-moments)"},
  {from:"lindelof", to:"schanuel", shared:"BC-KMS state"},
  {from:"lindelof", to:"turbulence", shared:"L-value (AMPLITUDE pin)"},
  {from:"lindelof", to:"turbulence", shared:"scaling dimension"},
  {from:"lindelof", to:"twin-primes", shared:"face-only (L-function bounds feed sieve)"},
  {from:"lindelof", to:"twin-primes", shared:"face-only (singular-series L-value)"},
  {from:"lindelof", to:"twin-primes", shared:"outgoing (via Cramér)"},
  {from:"lindelof", to:"twin-primes", shared:"zero distribution ($\\zeta$ bounds propagate)"},
  {from:"lindelof", to:"twin-primes", shared:"zero distribution (moments $T(\\log T)^{k^2}$)"},
  {from:"lindelof", to:"ym", shared:"BC-KMS state"},
  {from:"lindelof", to:"ym", shared:"face-only (AMPLITUDE ↔ CURVATURE adjacent in paper60 §13 table)"},
  {from:"lindelof", to:"ym", shared:"scaling dimension"},
  {from:"lindelof", to:"ym", shared:"scaling dimension (uniform amplitude bound)"},
  {from:"ns", to:"pvnp", shared:"face-only (SYMMETRY)"},
  {from:"ns", to:"pvnp", shared:"spectral gap"},
  {from:"ns", to:"qg5d", shared:"KK mode index"},
  {from:"ns", to:"qg5d", shared:"spectral gap"},
  {from:"ns", to:"qg5d", shared:"spectral gap (regularity scale), ergodic property (gradient flow contractivity), scaling dimension (energy scale)"},
  {from:"ns", to:"rh", shared:"BC-KMS state"},
  {from:"ns", to:"sato-tate", shared:"ergodic property (MEASURE face analog)"},
  {from:"ns", to:"turbulence", shared:"KK mode index"},
  {from:"ns", to:"turbulence", shared:"boundary condition"},
  {from:"ns", to:"turbulence", shared:"boundary condition (Clay-adjacent wall-family)"},
  {from:"ns", to:"turbulence", shared:"ergodic property"},
  {from:"ns", to:"turbulence", shared:"ergodic property (energy cascade)"},
  {from:"ns", to:"turbulence", shared:"scaling dimension"},
  {from:"ns", to:"turbulence", shared:"spectral gap"},
  {from:"ns", to:"ym", shared:"C*-algebra structure"},
  {from:"ns", to:"ym", shared:"C*-algebra structure (SYMMETRY-face analog)"},
  {from:"ns", to:"ym", shared:"C*-algebra structure (energy-momentum tensor regularity)"},
  {from:"ns", to:"ym", shared:"KK mode index + spectral gap"},
  {from:"ns", to:"ym", shared:"boundary condition (AMPLITUDE wall structure)"},
  {from:"ns", to:"ym", shared:"ergodic property (OS analog)"},
  {from:"ns", to:"ym", shared:"ergodic property (STRUCTURAL PARENT)"},
  {from:"ns", to:"ym", shared:"ergodic property (gradient-flow infrastructure)"},
  {from:"ns", to:"ym", shared:"face-only (form-factor regularity)"},
  {from:"ns", to:"ym", shared:"face-only (mass-gap-as-regularity-scale analog)"},
  {from:"ns", to:"ym", shared:"face-only (shared deviation analog)"},
  {from:"ns", to:"ym", shared:"scaling dimension (microlocal analog)"},
  {from:"ns", to:"ym", shared:"spectral gap"},
  {from:"opn", to:"pvnp", shared:"BC-KMS state + C*-algebra structure"},
  {from:"opn", to:"pvnp", shared:"rigidity pattern"},
  {from:"opn", to:"qg5d", shared:"BC-KMS state + C*-algebra structure"},
  {from:"opn", to:"qg5d", shared:"BC-KMS state, ergodic property (ITPFI decomposition)"},
  {from:"opn", to:"qg5d", shared:"ITPFI factor type"},
  {from:"opn", to:"qg5d", shared:"OPN's closure belongs to the programme hub"},
  {from:"opn", to:"rh", shared:"BC-KMS state"},
  {from:"opn", to:"rh", shared:"ITPFI factor type + BC-KMS state"},
  {from:"opn", to:"rh", shared:"ITPFI factor type + Euler product"},
  {from:"opn", to:"rh", shared:"L-value (conditional cascade from Route 6c)"},
  {from:"opn", to:"rh", shared:"L-value + spectral gap"},
  {from:"opn", to:"twin-primes", shared:"$\\mu_p$ generation / ARITHMETIC face"},
  {from:"opn", to:"twin-primes", shared:"$\\mu_p$ generators / BC entry"},
  {from:"opn", to:"twin-primes", shared:"additive-multiplicative wall structure"},
  {from:"opn", to:"twin-primes", shared:"zero distribution (explicit formula)"},
  {from:"pvnp", to:"qg5d", shared:"C*-algebra structure), spectral gap (Popa rigidity), ITPFI factor type (III₁)"},
  {from:"pvnp", to:"rh", shared:"BC-KMS state"},
  {from:"pvnp", to:"rh", shared:"C\\*-algebra structure"},
  {from:"pvnp", to:"rh", shared:"C\\*-algebra structure (BC algebra groupoid)"},
  {from:"pvnp", to:"rh", shared:"C\\*-algebra structure (non-injectivity of BC-algebra)"},
  {from:"pvnp", to:"rh", shared:"ITPFI factor type"},
  {from:"pvnp", to:"rh", shared:"ITPFI factor type (III$_1$)"},
  {from:"pvnp", to:"rh", shared:"spectral gap"},
  {from:"pvnp", to:"sato-tate", shared:"ITPFI factor type (type III$_1$ Popa rigidity)"},
  {from:"pvnp", to:"sato-tate", shared:"ergodic property (Berry-Esseen CLT $C/\\sqrt{k}$)"},
  {from:"pvnp", to:"sato-tate", shared:"ergodic property (MEASURE face)"},
  {from:"pvnp", to:"turbulence", shared:"ITPFI factor type"},
  {from:"pvnp", to:"turbulence", shared:"holonomy"},
  {from:"pvnp", to:"turbulence", shared:"scaling dimension"},
  {from:"pvnp", to:"twin-primes", shared:"L-value (parity barrier / Popa rigidity analog)"},
  {from:"pvnp", to:"twin-primes", shared:"scaling dimension"},
  {from:"pvnp", to:"twin-primes", shared:"scaling dimension (integer count)"},
  {from:"pvnp", to:"twin-primes", shared:"zero distribution (sine-kernel universality class)"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"BC-KMS state + ITPFI factor type (DIRECT parent)"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"C*-algebra structure (conditional structural step)"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"C*-algebra structure (full side DIRECT parent)"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"C*-algebra structure (fullness dichotomy engine)"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"C*-algebra structure (non-full side DIRECT parent)"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"C\\*-algebra structure (continuous BC fullness"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"C\\*-algebra structure (continuous BC fullness analog"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"Galois representation (clone / polymorphism ↔ GCT polynomial representation)"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"Galois representation (polymorphism-algebra ↔ polynomial-algebra classification)"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"ergodic property (strong ergodicity DYNAMICAL partner)"},
  {from:"pvnp", to:"vp-vs-vnp", shared:"scaling dimension (NP-complete ↔ VNP-complete target)"},
  {from:"pvnp", to:"ym", shared:"(outer-ring Clay-grade closure)"},
  {from:"pvnp", to:"ym", shared:"BC-KMS state"},
  {from:"pvnp", to:"ym", shared:"BC-KMS state (local C\\*-algebras)"},
  {from:"pvnp", to:"ym", shared:"C\\*-algebra structure (fullness ↔ mass gap as RIGIDITY)"},
  {from:"pvnp", to:"ym", shared:"C\\*-algebra structure (non-amenable-type III$_1$)"},
  {from:"pvnp", to:"ym", shared:"C\\*-algebra structure (operator-valued distribution analog)"},
  {from:"pvnp", to:"ym", shared:"C\\*-algebra structure (rigid dichotomy)"},
  {from:"pvnp", to:"ym", shared:"C\\*-algebra structure (spectral gap ↔ fullness-gap)"},
  {from:"pvnp", to:"ym", shared:"critical exponent (Popa-rigidity analog)"},
  {from:"pvnp", to:"ym", shared:"critical exponent (exponential growth rate)"},
  {from:"pvnp", to:"ym", shared:"ergodic property"},
  {from:"pvnp", to:"ym", shared:"ergodic property (gradient-flow strong ergodicity)"},
  {from:"pvnp", to:"ym", shared:"ergodic property (pigeonhole-on-compact-group)"},
  {from:"pvnp", to:"ym", shared:"ergodic property + C\\*-algebra structure"},
  {from:"pvnp", to:"ym", shared:"gauge class"},
  {from:"pvnp", to:"ym", shared:"gauge class (clone class $\\leftrightarrow$ gauge-group class)"},
  {from:"pvnp", to:"ym", shared:"gauge class (non-amenable / non-compact group)"},
  {from:"pvnp", to:"ym", shared:"gauge class (rigidity classification)"},
  {from:"pvnp", to:"ym", shared:"holonomy (unitary holonomy of polymorphism ↔ gauge holonomy)"},
  {from:"pvnp", to:"ym", shared:"scaling dimension"},
  {from:"pvnp", to:"ym", shared:"scaling dimension (Popa contraction analog)"},
  {from:"pvnp", to:"ym", shared:"scaling dimension (outer-ring Clay-translation layer)"},
  {from:"pvnp", to:"ym", shared:"spectral gap"},
  {from:"qg5d", to:"rh", shared:"BC-KMS state, ergodic property"},
  {from:"qg5d", to:"rh", shared:"BC-KMS state, spectral gap (Boegli H1/H2), ergodic property (type III₁), L-value (ζ(s) itself)"},
  {from:"qg5d", to:"rh", shared:"C*-algebra structure, BC-KMS state, spectral gap"},
  {from:"qg5d", to:"rh", shared:"ITPFI factor type + BC-KMS state"},
  {from:"qg5d", to:"rh", shared:"spectral gap"},
  {from:"qg5d", to:"rh", shared:"spectral gap, C*-algebra structure"},
  {from:"qg5d", to:"rh", shared:"spectral gap, holonomy"},
  {from:"qg5d", to:"sato-tate", shared:"BC-KMS state / ITPFI factor type"},
  {from:"qg5d", to:"sato-tate", shared:"BC-KMS state / spectral structure"},
  {from:"qg5d", to:"sato-tate", shared:"Galois representation / holonomy"},
  {from:"qg5d", to:"sato-tate", shared:"ergodic property/conjugacy), BC-KMS state"},
  {from:"qg5d", to:"schanuel", shared:"BC-KMS state"},
  {from:"qg5d", to:"schanuel", shared:"Galois representation"},
  {from:"qg5d", to:"schanuel", shared:"monodromy / $P_D$ inheritance"},
  {from:"qg5d", to:"schanuel", shared:"scaling dimension"},
  {from:"qg5d", to:"schanuel", shared:"scaling dimension, L-value"},
  {from:"qg5d", to:"turbulence", shared:"KK mode index"},
  {from:"qg5d", to:"turbulence", shared:"L-value"},
  {from:"qg5d", to:"turbulence", shared:"scaling dimension (K41 exponents), ergodic property (cascade mixing)"},
  {from:"qg5d", to:"turbulence", shared:"spectral gap"},
  {from:"qg5d", to:"twin-primes", shared:"zero distribution (spectral side underwrites)"},
  {from:"qg5d", to:"twin-primes", shared:"zero distribution, BC-KMS state (Hecke ℕ* generators μ_p)"},
  {from:"qg5d", to:"vp-vs-vnp", shared:"C*-algebra structure (continuous version), scaling dimension (algebraic complexity)"},
  {from:"qg5d", to:"vp-vs-vnp", shared:"C*-algebra structure (explicit edge)"},
  {from:"qg5d", to:"ym", shared:"critical exponent"},
  {from:"qg5d", to:"ym", shared:"scaling dimension (AF inheritance)"},
  {from:"qg5d", to:"ym", shared:"scaling dimension / K"},
  {from:"qg5d", to:"ym", shared:"spectral gap"},
  {from:"qg5d", to:"ym", shared:"spectral gap (IR equivalence)"},
  {from:"qg5d", to:"ym", shared:"spectral gap, KK mode index, C*-algebra structure (OS)"},
  {from:"rh", to:"sato-tate", shared:"BC-KMS state (same $\\omega_1$, same algebra)"},
  {from:"rh", to:"sato-tate", shared:"ergodic property (MEASURE canonical)"},
  {from:"rh", to:"sato-tate", shared:"spectral structure (motivic BC extension)"},
  {from:"rh", to:"sato-tate", shared:"zero distribution (spec$(D_\\infty) = \\{\\gamma_n\\}$)"},
  {from:"rh", to:"schanuel", shared:"BC-KMS state, spectral-triple construction"},
  {from:"rh", to:"schanuel", shared:"parent edge (inherit spectrum)"},
  {from:"rh", to:"schanuel", shared:"spectral content (INPUT hypothesis)"},
  {from:"rh", to:"schanuel", shared:"zero distribution"},
  {from:"rh", to:"schanuel", shared:"zero distribution (simplicity prerequisite)"},
  {from:"rh", to:"schanuel", shared:"zero distribution (upstream dependency)"},
  {from:"rh", to:"turbulence", shared:"BC-KMS state"},
  {from:"rh", to:"turbulence", shared:"L-value"},
  {from:"rh", to:"twin-primes", shared:"ARITHMETIC (Euler product)"},
  {from:"rh", to:"twin-primes", shared:"L-value (Mellin-bridge narrowness)"},
  {from:"rh", to:"twin-primes", shared:"L-value (arithmetic consequence)"},
  {from:"rh", to:"twin-primes", shared:"critical exponent (ARITHMETIC canonical)"},
  {from:"rh", to:"twin-primes", shared:"zero distribution (BC spectrum identification)"},
  {from:"rh", to:"twin-primes", shared:"zero distribution (Bombieri-Vinogradov)"},
  {from:"rh", to:"twin-primes", shared:"zero distribution (explicit formula)"},
  {from:"rh", to:"vp-vs-vnp", shared:"C*-algebra structure (BC-algebra fullness analog on continuous-spectrum side)"},
  {from:"rh", to:"vp-vs-vnp", shared:"C*-algebra structure (continuous BC via paper61 §10 Branch D resolvent)"},
  {from:"rh", to:"vp-vs-vnp", shared:"scaling dimension (zeta-regularization at short-distance side, alternative P5 reading)"},
  {from:"rh", to:"ym", shared:"BC-KMS state"},
  {from:"rh", to:"ym", shared:"C*-algebra structure"},
  {from:"rh", to:"ym", shared:"ergodic property"},
  {from:"rh", to:"ym", shared:"ergodic property (BC-algebra)"},
  {from:"rh", to:"ym", shared:"face-only (SYMMETRY canonical)"},
  {from:"rh", to:"ym", shared:"scaling dimension"},
  {from:"rh", to:"ym", shared:"scaling dimension (uniform analyticity radius ↔ uniform $H^1$ bound)"},
  {from:"rh", to:"ym", shared:"scaling dimension (uniform resolvent bound)"},
  {from:"rh", to:"ym", shared:"scaling dimension (zeta regularization)"},
  {from:"rh", to:"ym", shared:"spectral gap"},
  {from:"rh", to:"ym", shared:"spectral gap (uniform-constant)"},
  {from:"rh", to:"ym", shared:"spectral gap / uniform-constant"},
  {from:"sato-tate", to:"turbulence", shared:"face-only (MEASURE vs SPREAD adjacency)"},
  {from:"sato-tate", to:"twin-primes", shared:"C*-algebra structure (Hecke-asymmetry)"},
  {from:"sato-tate", to:"twin-primes", shared:"face-only (local-factor extraction)"},
  {from:"sato-tate", to:"twin-primes", shared:"zero distribution (Haar pushforward)"},
  {from:"sato-tate", to:"ym", shared:"face-only (BC-KMS state restricted to local fields)"},
  {from:"schanuel", to:"twin-primes", shared:"face-only (ARITHMETIC South trough)"},
  {from:"schanuel", to:"ym", shared:"BC-KMS state, spectral-triple structure"},
  {from:"turbulence", to:"ym", shared:"BC-KMS state (OS analog)"},
  {from:"turbulence", to:"ym", shared:"KK mode index + spectral gap foundation"},
  {from:"turbulence", to:"ym", shared:"ergodic property"},
  {from:"turbulence", to:"ym", shared:"scaling dimension (Clay-adjacent wall-family)"},
  {from:"turbulence", to:"ym", shared:"spectral gap"},
  {from:"twin-primes", to:"ym", shared:"KK mode index (integer-power-sum on circle)"},
  {from:"twin-primes", to:"ym", shared:"face-only (Newton integer lattice on the circle)"},
  {from:"vp-vs-vnp", to:"ym", shared:"C*-algebra structure (mass gap rigidity ↔ fullness-as-gap rigidity)"},
  {from:"vp-vs-vnp", to:"ym", shared:"gauge class (group complexification P1 shared)"},
  {from:"vp-vs-vnp", to:"ym", shared:"gauge class (group complexification)"},
  {from:"vp-vs-vnp", to:"ym", shared:"scaling dimension (final-mechanical-closure conditional analog)"},
];

// Per-vertex cross-cut counts (unique edge endpoints, counted once per edge).
const ATLAS_COUNTS = {
  "qg5d": 88,
  "ym": 121,
  "rh": 147,
  "bsd": 94,
  "pvnp": 103,
  "hodge": 64,
  "ns": 39,
  "grh": 61,
  "bgs": 95,
  "baum-connes": 69,
  "katz-sarnak": 84,
  "goldbach": 66,
  "twin-primes": 75,
  "cramer": 81,
  "lindelof": 48,
  "h12": 54,
  "turbulence": 38,
  "vp-vs-vnp": 36,
  "abc": 44,
  "opn": 44,
  "collatz": 50,
  "lehmer": 61,
  "sato-tate": 68,
  "schanuel": 42,
  "hilbert-6": 26,
};

// Per-vertex distinct neighbour counts.
const ATLAS_NEIGHBOURS = {
  "qg5d": 24,
  "ym": 22,
  "rh": 24,
  "bsd": 18,
  "pvnp": 22,
  "hodge": 14,
  "ns": 13,
  "grh": 16,
  "bgs": 24,
  "baum-connes": 23,
  "katz-sarnak": 20,
  "goldbach": 18,
  "twin-primes": 19,
  "cramer": 19,
  "lindelof": 19,
  "h12": 15,
  "turbulence": 13,
  "vp-vs-vnp": 11,
  "abc": 15,
  "opn": 13,
  "collatz": 16,
  "lehmer": 19,
  "sato-tate": 20,
  "schanuel": 14,
  "hilbert-6": 13,
};

if (typeof window !== 'undefined') {
  window.ATLAS_EDGES = ATLAS_EDGES;
  window.ATLAS_COUNTS = ATLAS_COUNTS;
  window.ATLAS_NEIGHBOURS = ATLAS_NEIGHBOURS;
}
