// Auto-generated by visualization/torus/build.py -- do not edit by hand.
// Generated 2026-04-14T17:33:04
// Regenerate: python3 visualization/torus/build.py

const TORUS_DATA = {
  "generated_at": "2026-04-14T17:33:04",
  "generator": "visualization/torus/build.py",
  "definition": {
    "one_line": "The e-circle (geometric, U(1), the fifth dimension) and the modular flow (spectral, KMS_1 orbit) are the two generating circles of a torus T^2 = S^1_geo x S^1_spec. The ten faces live on its surface.",
    "crossed_product": "A_BC x_sigma R  (BC algebra crossed with modular flow)",
    "quotes": [
      {
        "source": "paper60 \u00a717",
        "text": "The two circles are not independent. They are linked by the deepest structure in operator algebra: the crossed product."
      },
      {
        "source": "paper60 \u00a717",
        "text": "is the operator algebra that encodes BOTH circles simultaneously. It is Connes' type II$_\\infty$ algebra -- the \"unfolding\" of the type III$_1$ factor that makes the modular flow visible as a geometric action. The crossed product IS the torus: one factor is the geometric circle (the BC algebra on $U(1)$), the other is the spectral circle (the flow $\\mathbb{R}$ compactified by the KMS periodicity)."
      },
      {
        "source": "paper60 \u00a717",
        "text": "This is not a metaphor. The crossed product construction is the STANDARD way to build a torus from a circle and an action: given $S^1$ and an automorphism $\\sigma: S^1 \\to S^1$, the mapping torus $S^1 \\rtimes_\\sigma \\mathbb{R}/\\mathbb{Z}$ is $T^2$. When $\\sigma$ is the identity, the mapping torus is the product torus $S^1 \\times S^1$. When $\\sigma$ is nontrivial, the mapping torus is a twisted tor"
      },
      {
        "source": "paper60 \u00a718",
        "text": "**Transversally:** The circles cross cleanly. At each intersection point, the tangent directions of the two circles span the full tangent plane of the torus. The intersection is STABLE -- small perturbations of either circle do not destroy the crossing; they merely shift it slightly. The intersection points are isolated, discrete, and well-behaved."
      },
      {
        "source": "paper60 \u00a718",
        "text": "**Non-transversally:** The circles touch tangentially, or one circle grazes the other, or the intersection has higher multiplicity. The intersection is UNSTABLE -- a small perturbation can create or destroy crossing points, or split a tangential touching into two crossings, or cause a zero to drift off the intersection locus entirely."
      },
      {
        "source": "paper60 \u00a719",
        "text": "The ten faces of the e-circle are ten PROPERTIES of the circle -- ten questions you can ask about it, ten conjectures about its nature. TOPOLOGY asks what can live on it. DYNAMICS asks how the flow traverses it. CURVATURE asks how connections curve. Each face is a projection: one community, one domain, one question, one conjecture."
      },
      {
        "source": "paper60 \u00a719",
        "text": "Recall the architecture. The geometric circle (the e-dimension, $U(1)$, radius $R$) carries five faces: TOPOLOGY, HARMONICS, MEASURE, CURVATURE, SPREAD. The spectral circle (the modular flow $\\sigma_t$, the KMS$_1$ orbit) carries five faces: DYNAMICS, AMPLITUDE, SYMMETRY, ARITHMETIC, RESONANCE. The torus $T^2 = S^1_{\\text{geo}} \\times S^1_{\\text{spec}}$ is the surface on which all ten faces coexis"
      }
    ],
    "source_files": [
      "paper60/17-two-circles-one-torus.md",
      "paper60/18-riemann-zeros-as-intersection.md",
      "paper60/19-rh-as-existence-of-the-torus.md"
    ]
  },
  "radii": {
    "physical_R_microns": 10.1,
    "major_R_visual": 3.0,
    "minor_r_visual": 1.0,
    "note": "Paper 60 specifies R ~ 10.10 um for the physical e-circle but does not give a numerical minor-radius (tube) value for the torus embedding. Major/minor radii for the visualization are visual defaults."
  },
  "faces": [
    {
      "key": "TOPOLOGY",
      "conj": "Lehmer",
      "question": "What can LIVE on it?",
      "circle": "geometric",
      "col": 0,
      "conf": 4.0,
      "paper": "Paper 42",
      "face_num": 1,
      "u": 0.0,
      "v": 1.5707963267948966
    },
    {
      "key": "DYNAMICS",
      "conj": "Cramer",
      "question": "How does the flow TRAVERSE it?",
      "circle": "spectral",
      "col": 0,
      "conf": 5.0,
      "paper": "Paper 43",
      "face_num": 2,
      "u": 0.0,
      "v": -1.5707963267948966
    },
    {
      "key": "HARMONICS",
      "conj": "Collatz",
      "question": "How do modes MIX on it?",
      "circle": "geometric",
      "col": 1,
      "conf": 4.0,
      "paper": "Paper 41",
      "face_num": 3,
      "u": 1.2566370614359172,
      "v": 1.5707963267948966
    },
    {
      "key": "AMPLITUDE",
      "conj": "Lindeloef",
      "question": "How LOUD can it get?",
      "circle": "spectral",
      "col": 1,
      "conf": 7.0,
      "paper": "Paper 45",
      "face_num": 5,
      "u": 1.2566370614359172,
      "v": -1.5707963267948966
    },
    {
      "key": "CURVATURE",
      "conj": "Yang-Mills",
      "question": "How do connections CURVE on it?",
      "circle": "geometric",
      "col": 2,
      "conf": 9.5,
      "paper": "Paper 08",
      "face_num": 7,
      "u": 2.5132741228718345,
      "v": 1.5707963267948966
    },
    {
      "key": "SYMMETRY",
      "conj": "Katz-Sarnak",
      "question": "Which GROUP acts on it?",
      "circle": "spectral",
      "col": 2,
      "conf": 7.0,
      "paper": "Paper 46",
      "face_num": 6,
      "u": 2.5132741228718345,
      "v": -1.5707963267948966
    },
    {
      "key": "MEASURE",
      "conj": "Sato-Tate",
      "question": "How do angles DISTRIBUTE on it?",
      "circle": "geometric",
      "col": 3,
      "conf": 6.0,
      "paper": "Paper 44",
      "face_num": 4,
      "u": 3.7699111843077517,
      "v": 1.5707963267948966
    },
    {
      "key": "ARITHMETIC",
      "conj": "Goldbach/Twin",
      "question": "How do integers LATTICE on it?",
      "circle": "spectral",
      "col": 3,
      "conf": 1.0,
      "paper": "Papers 33-34",
      "face_num": 8,
      "u": 3.7699111843077517,
      "v": -1.5707963267948966
    },
    {
      "key": "SPREAD",
      "conj": "QUE (Lindenstrauss)",
      "question": "How do eigenmodes SPREAD?",
      "circle": "both",
      "col": 4,
      "conf": 8.0,
      "paper": "Paper 48",
      "face_num": 10,
      "u": 5.026548245743669,
      "v": 0.0
    },
    {
      "key": "RESONANCE",
      "conj": "Selberg 1/4",
      "question": "What frequencies are ALLOWED?",
      "circle": "spectral",
      "col": 4,
      "conf": 6.0,
      "paper": "Paper 47",
      "face_num": 9,
      "u": 5.026548245743669,
      "v": -1.5707963267948966
    }
  ],
  "vertices": [
    {
      "name": "QG5D",
      "pos": 0,
      "conf": 10.0,
      "zone": "NORTH",
      "u": 0.0,
      "v": 0.35
    },
    {
      "name": "YM",
      "pos": 1,
      "conf": 9.5,
      "zone": "NORTH",
      "u": 0.25132741228718347,
      "v": 0.35
    },
    {
      "name": "RH",
      "pos": 2,
      "conf": 8.0,
      "zone": "NORTH",
      "u": 0.5026548245743669,
      "v": 0.35
    },
    {
      "name": "Lindeloef",
      "pos": 3,
      "conf": 7.0,
      "zone": "EAST",
      "u": 0.7539822368615503,
      "v": 0.0
    },
    {
      "name": "GRH",
      "pos": 4,
      "conf": 7.0,
      "zone": "EAST",
      "u": 1.0053096491487339,
      "v": 0.0
    },
    {
      "name": "BGS",
      "pos": 5,
      "conf": 7.0,
      "zone": "EAST",
      "u": 1.2566370614359172,
      "v": 0.0
    },
    {
      "name": "BSD",
      "pos": 6,
      "conf": 9.0,
      "zone": "NORTH",
      "u": 1.5079644737231006,
      "v": 0.35
    },
    {
      "name": "PvNP",
      "pos": 7,
      "conf": 7.0,
      "zone": "EAST",
      "u": 1.7592918860102844,
      "v": 0.0
    },
    {
      "name": "H6",
      "pos": 8,
      "conf": 7.0,
      "zone": "WEST",
      "u": 2.0106192982974678,
      "v": 0.0
    },
    {
      "name": "H12",
      "pos": 9,
      "conf": 2.0,
      "zone": "SOUTH",
      "u": 2.261946710584651,
      "v": -0.35
    },
    {
      "name": "Cramer",
      "pos": 10,
      "conf": 5.0,
      "zone": "EAST",
      "u": 2.5132741228718345,
      "v": 0.0
    },
    {
      "name": "NS",
      "pos": 11,
      "conf": 4.0,
      "zone": "EAST",
      "u": 2.764601535159018,
      "v": 0.0
    },
    {
      "name": "Hodge",
      "pos": 12,
      "conf": 3.0,
      "zone": "WEST",
      "u": 3.015928947446201,
      "v": 0.0
    },
    {
      "name": "Turb",
      "pos": 13,
      "conf": 2.0,
      "zone": "SOUTH",
      "u": 3.267256359733385,
      "v": -0.35
    },
    {
      "name": "Katz-Sarnak",
      "pos": 14,
      "conf": 7.0,
      "zone": "EAST",
      "u": 3.518583772020569,
      "v": 0.0
    },
    {
      "name": "Sato-Tate",
      "pos": 15,
      "conf": 6.0,
      "zone": "WEST",
      "u": 3.7699111843077517,
      "v": 0.0
    },
    {
      "name": "Twin",
      "pos": 16,
      "conf": 1.0,
      "zone": "SOUTH",
      "u": 4.0212385965949355,
      "v": -0.35
    },
    {
      "name": "Goldbach",
      "pos": 17,
      "conf": 1.0,
      "zone": "SOUTH",
      "u": 4.272566008882119,
      "v": -0.35
    },
    {
      "name": "Schanuel",
      "pos": 18,
      "conf": 1.0,
      "zone": "SOUTH",
      "u": 4.523893421169302,
      "v": -0.35
    },
    {
      "name": "OPN",
      "pos": 19,
      "conf": 4.0,
      "zone": "WEST",
      "u": 4.775220833456485,
      "v": 0.0
    },
    {
      "name": "Collatz",
      "pos": 20,
      "conf": 4.0,
      "zone": "WEST",
      "u": 5.026548245743669,
      "v": 0.0
    },
    {
      "name": "Lehmer",
      "pos": 21,
      "conf": 4.0,
      "zone": "WEST",
      "u": 5.277875658030852,
      "v": 0.0
    },
    {
      "name": "ABC",
      "pos": 22,
      "conf": 1.0,
      "zone": "SOUTH",
      "u": 5.529203070318036,
      "v": -0.35
    },
    {
      "name": "B-C",
      "pos": 23,
      "conf": 3.0,
      "zone": "WEST",
      "u": 5.7805304826052195,
      "v": 0.0
    },
    {
      "name": "VP",
      "pos": 24,
      "conf": 1.0,
      "zone": "SOUTH",
      "u": 6.031857894892402,
      "v": -0.35
    }
  ],
  "zeros": [
    {
      "index": 1,
      "gamma": 14.134725,
      "u": 1.568354385640827,
      "v": 0.0
    },
    {
      "index": 2,
      "gamma": 21.02204,
      "u": 2.172484078461242,
      "v": 0.0
    },
    {
      "index": 3,
      "gamma": 25.010858,
      "u": 6.16130207846124,
      "v": 0.0
    },
    {
      "index": 4,
      "gamma": 30.424876,
      "u": 5.292134771281656,
      "v": 0.0
    },
    {
      "index": 5,
      "gamma": 32.935062,
      "u": 1.519135464102071,
      "v": 0.0
    },
    {
      "index": 6,
      "gamma": 37.586178,
      "u": 6.170251464102066,
      "v": 0.0
    },
    {
      "index": 7,
      "gamma": 40.918719,
      "u": 3.2196071569224856,
      "v": 0.0
    },
    {
      "index": 8,
      "gamma": 43.327073,
      "u": 5.627961156922481,
      "v": 0.0
    },
    {
      "index": 9,
      "gamma": 48.005151,
      "u": 4.022853849742894,
      "v": 0.0
    },
    {
      "index": 10,
      "gamma": 49.773832,
      "u": 5.791534849742895,
      "v": 0.0
    },
    {
      "index": 11,
      "gamma": 52.970321,
      "u": 2.7048385425633086,
      "v": 0.0
    },
    {
      "index": 12,
      "gamma": 56.446248,
      "u": 6.180765542563307,
      "v": 0.0
    }
  ],
  "south_trough": {
    "definition": "The ring's confidence distribution is not uniform. It is elliptical, with a NORTH pole (QG5D at 10/10) and a SOUTH trough (Goldbach, Twin Primes, Schanuel, VP at 1/10). On the torus, the south trough is the set of ring-vertex positions on the lower half of the major circle (v < 0 band on the tube).",
    "south_vertices": [
      "H12",
      "Turb",
      "Twin",
      "Goldbach",
      "Schanuel",
      "ABC",
      "VP"
    ],
    "avg_conf_south": 1.29,
    "avg_conf_north": 9.12,
    "confidence_ratio_N_over_S": 7.1,
    "ellipse_major_axis": "NORTH-SOUTH",
    "ellipse_minor_axis": "EAST-WEST",
    "quotes": [
      "*The discovery of the ring's lopsidedness as a structural diagnostic. The ellipse IS the X-ray. The direction of the lopsidedness tells us where to excise, bypass, and repair.*",
      "But we treated the ring as a CIRCLE \u2014 25 equally-weighted stops on a geometric object. We didn't see that the ring ITSELF had geometry. We didn't see that the confidence distribution was LOPSIDED. We didn't see that the lopsidedness was a DIAGNOSTIC.",
      "The ellipse IS the X-ray. The direction of the lopsidedness is where the programme needs to focus. The ring is not a circle of equal stops \u2014 it is an ellipse with a NORTH POLE of completed work and a SOUTH TROUGH of unthickened frontier. Every future traversal must concentrate on the South. The North needs protection, not work."
    ],
    "source": "paper60 \u00a728"
  },
  "explanation": [
    {
      "idx": 1,
      "title": "Start from M^5 = M^4 x S^1",
      "body": "Paper 1's postulate: spacetime is five-dimensional, and the fifth dimension is a circle. Mathematically S^1 = U(1) = R/2piZ with R ~ 10.10 um. This is the FIRST (geometric) circle -- the substrate on which things live.",
      "cite": "paper60 \u00a717 & \u00a703; Paper 1 \u00a71",
      "highlight": "geometric_circle"
    },
    {
      "idx": 2,
      "title": "Add the modular flow -- the SECOND circle",
      "body": "The BC algebra at beta=1 is a type III_1 factor. Its modular flow sigma_t acts as a one-parameter automorphism that closes up under the KMS periodicity. This is the SECOND (spectral) circle -- the flow that traverses the substrate.",
      "cite": "paper60 \u00a717; Paper 12 \u00a723",
      "highlight": "spectral_circle"
    },
    {
      "idx": 3,
      "title": "The crossed product IS the torus",
      "body": "The crossed product A_BC rtimes_sigma R encodes both circles simultaneously. The geometric and spectral circles are its two generating factors. That is the torus T^2 = S^1_geo x S^1_spec. This is not a metaphor -- it is the type II_\u221e unfolding of the type III_1 factor.",
      "cite": "paper60 \u00a717",
      "highlight": "torus_surface"
    },
    {
      "idx": 4,
      "title": "The 10 faces live on the torus surface",
      "body": "Five GEOMETRIC faces (TOPOLOGY, HARMONICS, MEASURE, CURVATURE, SPREAD) sit along the major (geometric) direction. Five SPECTRAL faces (DYNAMICS, AMPLITUDE, SYMMETRY, ARITHMETIC, RESONANCE) sit along the minor (spectral) direction. SPREAD (QUE) bridges both circles -- it sits at the equator. Each face is one of the world's famous unsolved problems (or a recently-proved theorem).",
      "cite": "paper60 \u00a717 grid, \u00a720 table, \u00a728",
      "highlight": "faces"
    },
    {
      "idx": 5,
      "title": "The 25 ring vertices sit on the major loop",
      "body": "The programme's methodology is a ring of 25 vertices (Paper 60 \u00a722, \u00a728). On the torus, these vertices distribute around the major (geometric) loop. Confidence scores push NORTH vertices toward the outer top of the tube (v > 0) and SOUTH vertices toward the inner bottom (v < 0), producing the ellipse.",
      "cite": "paper60 \u00a728",
      "highlight": "vertices"
    },
    {
      "idx": 6,
      "title": "The south trough + ellipse diagnostic",
      "body": "The confidence distribution is lopsided. NORTH average ~9.1, SOUTH average ~1.4 -- a 10x dipole. The major axis of the ellipse runs NORTH-SOUTH. On the torus, the SOUTH TROUGH is the arc of the major circle where low-confidence arithmetic faces (Goldbach, Twin Primes, Schanuel, VP, ABC) cluster. The direction of the lopsidedness tells the programme where to focus: SOUTH.",
      "cite": "paper60 \u00a728 'The South Trough Needs Lifting'",
      "highlight": "south_trough"
    },
    {
      "idx": 7,
      "title": "Riemann zeros are the intersection points",
      "body": "On the torus the geometric and spectral circles intersect at discrete points -- the Riemann zeros {gamma_n}. RH says the intersections are transversal: every zero sits at a clean crossing on the torus surface, none wander into the interior. RH is the EXISTENCE of the torus as a well-formed surface.",
      "cite": "paper60 \u00a718, \u00a719",
      "highlight": "zeros"
    }
  ],
  "quotes": [
    {
      "source": "paper60 \u00a717",
      "text": "\"Wait -- is it a circle or a torus?\" Both. (G, April 14, 2026)"
    },
    {
      "source": "paper60 \u00a717",
      "text": "Not one circle. Two. And two circles, linked, make a torus."
    },
    {
      "source": "paper60 \u00a718",
      "text": "The zeros are where the two circles cross. Every Riemann zero is simultaneously a point on the geometric circle and a point on the spectral circle."
    },
    {
      "source": "paper60 \u00a719",
      "text": "The Riemann Hypothesis is not a face. It is the EXISTENCE of the torus."
    },
    {
      "source": "paper60 \u00a719",
      "text": "\"The physics IS the mathematics.\" The physics (geometric circle) and mathematics (spectral circle) are the two generating circles of one torus."
    },
    {
      "source": "paper60 \u00a720",
      "text": "The ring has a NORTH POLE (QG5D at 10/10) and a SOUTH TROUGH (Goldbach/Twin Primes/Schanuel/VP at 1/10). The confidence drops 10x from pole to trough. This is an ellipse, not a circle."
    },
    {
      "source": "paper60 \u00a728",
      "text": "\"i am in love with this picture we just discovered everything about the e-circle!! the direction of the lopsidedness is where we need to focus our excision/bypass/repair exercises.\" -- G, April 14, 2026"
    }
  ],
  "source_files": [
    "paper60-the-geometry-of-the-circle/00-table-of-contents.md",
    "paper60-the-geometry-of-the-circle/07-face-1-topology-lehmer.md",
    "paper60-the-geometry-of-the-circle/08-face-2-dynamics-cramer.md",
    "paper60-the-geometry-of-the-circle/09-face-3-harmonics-collatz.md",
    "paper60-the-geometry-of-the-circle/10-face-4-measure-sato-tate.md",
    "paper60-the-geometry-of-the-circle/11-face-5-amplitude-lindelof.md",
    "paper60-the-geometry-of-the-circle/12-face-6-symmetry-katz-sarnak.md",
    "paper60-the-geometry-of-the-circle/13-face-7-curvature-yang-mills.md",
    "paper60-the-geometry-of-the-circle/14-face-8-arithmetic-goldbach-twin-primes.md",
    "paper60-the-geometry-of-the-circle/17-two-circles-one-torus.md",
    "paper60-the-geometry-of-the-circle/18-riemann-zeros-as-intersection.md",
    "paper60-the-geometry-of-the-circle/19-rh-as-existence-of-the-torus.md",
    "paper60-the-geometry-of-the-circle/20-the-ellipse-and-the-missing-faces.md",
    "paper60-the-geometry-of-the-circle/21-the-s-duality.md",
    "paper60-the-geometry-of-the-circle/25-the-opn-trigger.md",
    "paper60-the-geometry-of-the-circle/26-the-three-face-recognition.md",
    "paper60-the-geometry-of-the-circle/27-the-acceleration.md",
    "paper60-the-geometry-of-the-circle/28-the-south-trough-needs-lifting.md",
    "paper60-the-geometry-of-the-circle/29-the-signal-log.md"
  ],
  "face_count": 10,
  "vertex_count": 25,
  "zero_count": 12
};
